### ISSUE TITLE
Empty string not allowed crash

### ISSUE THREAD

**Issue by beboobailey** [ShetiPhian/Localizations-and-Issues#103]
Crafted an enderlink chest, placed it in the overworld, then crafted an enderlink bag, linked the bag to the chest. Tested the bag by placing something in it and viewed chest to confirm working.

Went to an RFTools dimension, right-clicked the enderlink bag to deposit my spoils and client crashed with `java.lang.IllegalArgumentException: Empty string not allowed`. 

Crash report:
[crash-2017-08-17_15.41.12-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/1232415/crash-2017-08-17_15.41.12-client.txt)

**Comment by ShetiPhian** [comment]
That bug is corrected in later builds, not for 1.10 though as it was removed from active development prior to the work around being implemented.
When I can I'll backport the fix, might be this weekend but I can't promise anything.

I never found out what caused the bug, just why it happened. 
For some reason the NBT data is wiped out client side so the data used in the GUI is missing.
The system was rewritten to be full server side with a custom packet for the GUI

**Comment by ShetiPhian** [comment]
I back ported the code, it needed a few changes to work on 1.10 though.

http://www.mediafire.com/file/abwiu75bsx67nh1/multistorage-1.10.0-1.2.19-TestBuild.jar

**Comment by ShetiPhian** [comment]
Fixed in 1.3.8
https://minecraft.curseforge.com/projects/multistorage/files/2470528
