### ISSUE TITLE
MultiStorage modifies the world from a Netty handler thread

### ISSUE THREAD

**Issue by Aaron1011** [ShetiPhian/Localizations-and-Issues#109]
Judging from [this stacktrace](https://pastebin.com/raw/aQhedqwW) (ignore the Sponge-related lines), `VaultHelper#removeDoorBlock` is being invoked (indirectly) from a packet handler. Since Forge runs all custom handlers on a Netty thread, rather than the server thread, this will cause all sorts of issues.

While an exception will probably not occur when Sponge is not installed, more subtle issues will almost certain result, as `World` is not thread-safe. If you could ensure that all world modifications happen on the server thread (through `MinecraftServer#addScheduledTask`), it would be extremely helpful.

**Comment by ShetiPhian** [comment]
I guess that 'Thread Safe' Netty example I based my 1.8 packet handler off of wasn't thread safe after all.

**Comment by ShetiPhian** [comment]
It looks like a rather simple fix. The packets IMessageHandler needs to call IThreadListener#addScheduledTask

I'm glad I coded things the way I did; (for all packets the handler onMessage method calls PacketPipeline#onMessage)
So rather then needing to fix every single packet in all my mods I just need to make a change in one method in ShetiPhianCore.

Since the issue is/was invisible to me, and you currently have an environment in which the error is reproducible, I'll give you the new build for checking.

http://www.mediafire.com/file/sw4eb6iq2c17nel/shetiphiancore-1.12.0-3.5.2.jar
http://www.mediafire.com/file/044nedf37on1618/shetiphiancore-1.11.0-3.4.7.jar


Non thread safe packets could explain the couple of issues that happened at random and appeared to happen for no reason.

**Comment by Aaron1011** [comment]
@destructor3: Can you see if that resolves your issue? ^

**Comment by destructor3** [comment]
Sadly I can't test it because all the other mods running for the public server are for 1.11 and 1.12, while FTB Beyond is currently running on 1.10.2, and the support for new versions is pretty poor for the users (while the modders are moving on). 

I could run a couple tests on a testserver but not on my main server which i'm testing now, when I have time; anyway I thank you all for this immediate response and fixes to improve the next versions for the community!

**Comment by ShetiPhian** [comment]
Here is a quick back port for 1.10
http://www.mediafire.com/file/c1vjot5cmyuzbud/shetiphiancore-1.10.0-3.3.11.jar

I'll add SpongeForge to my testing, might need to wait for a newer stable though as my 1.10 builds only get critical bug fixes now.

**Comment by ShetiPhian** [comment]
I've corrected the import issue the live environment didn't like, and had Sponge installed for some tests.
The fixed packet handler corrected a visual oddity in one of my GUIs, and appears to be the fix for another reported bug.

New build had been uploaded to Curse.
