### ISSUE TITLE
Crash when opening an enderlink bag

### ISSUE THREAD

**Issue by hfab** [ShetiPhian/Localizations-and-Issues#110]
In the FTB unstable 1.12 modpack I am using a couple of enderlink bags to send my mined items and blocks back to my base so I can keep mining. But every now and then the game crashes when I right click with an enderlink bag to open it. Replacing the multistorage mod in the pack (1.12.0-1.4.0.2) with the latest version (1.12.0-1.4.1) seems to make the crash occur more often.
[multistorage_crashreport.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/1283986/multistorage_crashreport.txt)

**Comment by ShetiPhian** [comment]
This might be due to a recently discovered error in my packet handler.
If this test build doesn't fix the issue, I may need to block JEI for displaying on the EnderBags
http://www.mediafire.com/file/sw4eb6iq2c17nel/shetiphiancore-1.12.0-3.5.2.jar

**Comment by ShetiPhian** [comment]
To go with that test build of ShetiPhianCore, here is one of MultiStorage
http://www.mediafire.com/file/i8ucnimo3lujimp/multistorage-1.12.0-1.4.2.jar

In that build I've switched from my own version of GuiContainer to using an access transformer on the original, this should improve mod compatibility.

I'm kinda stuck trying to solve this in the dark as I'm not getting the error myself, and the ConcurrentModificationException error itself lacks needed trouble shooting information.
The error happens when one system changes a list while another access it, the error only lists the last thing accessing the list (JEI) but not what list is being accessed or the other system that is involved.
All I have to go by is JEI is crashing on some ingredient list while my GUI is open.

**Comment by hfab** [comment]
The test build for shetiphiancore fixed the problem.
Thanks for the fast reaction.

**Comment by ShetiPhian** [comment]
Thank you,
My version of GuiContainer was based on an older one, in 1.12 GuiContainer no longer calls the tool-tip renderer, rather that is now up to individual GUI's.
