### ISSUE TITLE
Crashing while starting server.

### ISSUE THREAD

**Issue by Gbergz** [ShetiPhian/Localizations-and-Issues#111]
**Title**

I traced it down and as soon as i removed this mod. Everything worked.
Crashlog here:
[Pastebin](https://pastebin.com/mvgLF1Mb)

Latest Version of ShetiPhianCore:
1.12.0-3.5.2

(EDIT: A friend of mine says you need to sign it for 1.12.1)

**Comment by ShetiPhian** [comment]
Crash is due to a ConcurrentModificationException 
The loot tables are being accessed/edited incorrectly.

While Terraqueous does add to the loot tables, it only does so in the Forge provided LootTableLoadEvent where table manipulation is intended.

There is another mod in your pack interacting with the tables in a way that causes issues when another mod uses the Forge event to do so.
With my recent experience with thread safe issues, my guess is the other mod is accessing the tables from the wrong thread.

If you can pin down what the other mod is, I may be able to find the error, and maybe be able to work around it.

**Comment by Gbergz** [comment]
Hey again,i think i found the mod causing issues. Removing the Mod[ 'OreShrubs'](https://minecraft.curseforge.com/projects/ore-shrubs) makes the server work again.

**Comment by ShetiPhian** [comment]
Looking at their issue tracker (https://github.com/Lhykos/OreShrubs/issues), there is two other reports of this crash. 
It happens with no other mods installed, so its not a mod conflict, meaning that is nothing I can change to make it work.
There is one person saying they are not having the issue, so it is likely due to threading. Threading errors cause unpredictable and random issues.

The project page currently notes it doesn't work on 1.12.1
At the moment your options are to go back to 1.12.0 or with for OreShrubs to update to 1.12.1
