### ISSUE TITLE
[Minecraft 1.12.2 - Terraqueous 1.12.0 - 1.4.3] Cascading server death - Fix suggestion

### ISSUE THREAD

**Issue by VallenFrostweaver** [ShetiPhian/Localizations-and-Issues#120]
I have discovered something while playing the Radon modpack that Terraqueous has sadly been leading to my server running slower and slower until stopping. With flower spread turned on and trickster blooms included they spread as well. Trickster blooms then occasionally turn mobs into neutrals. This alone doesn't sound like much but when you factor in the next part it makes more sense. Chickens are neutrals and they lay eggs. This keeps cascading as more and more mobs are turned into neutrals creating chickens creating eggs etc. Last time I used "kill @e[type=item]" I removed about 15000 items and the large majority were eggs as I had chunk loading allowed as well for about 15 active players. I realize there are options to turn this off in the configs but it took a lot of time and effort of tracking the issues backwards until I could identify the problem. I would like to recommend that by default you set up the configs of this mod to _not_ turn mobs into neutrals and allow people to change it back in the configs. This should ensure less issues with server play in the end. Thanks for a cool mod. :)

**Comment by ShetiPhian** [comment]
Thank you for locating this issue and sorry for the radio silence, I wasn't sure the action I was going to take to fix this. (and then I got wrapped up in code and forgot too)

Just changing the default setting wouldn't work on existing worlds, players would need to revert it to default manually.
Renaming the option would force the new default, but still leaves the possibility of the issue.
Even with a warning someone my enable it and have no issues, when problem starts they may have forgotten about the setting.

So I removed the mob transmutation from the Trickster Bloom; transmutations needed to be something a user deliberately set up, not something that a generated world item does (especially on that is rather plentiful and can spread)

I first started working on a fluid you'd make from the flowers that would cause the transmutations.
Though I did get it working and only needed to add textures and recipes, a new issue was brought up. People use the flowers as base defense, being a fluid more or less forces everyone to have a moat.

With that idea scrapped I proceeded to create a new block 'Border'
![Borders.png](https://lh3.googleusercontent.com/SEH551quJ7fnGkzAaY7Wt6LvIhxrQzNXCXGGT4bCKwnSuoI7X1isc_1GonbhbUIxfmxGOIjQ_XSfKr0988KFOHt79dUcOp4hjtfPrEY04uYe3fO1Thar2_blhTtbpi_exEd5HSW_RNPosLShDMiooZXYaZXY-3aaVAq3IHwH83mWQzcyw7Kcr7w4kyPXU4Z4Y0hp6n89P57jVfJXM2lgia300eoe147H48MmoeBsuatP4CwlWgFfXHrj_U-TWSVszF4-CC5u0CGfMFo99yM0T15mtCQysg81pTK-qqC5NcIre6KwMgszbyTi_VYCt0f4FCwp309WdSSDaR3ZVrqmOiSa02G9hsG_gbNxUWeOsUv7fI0iiS0yxmUljTBBTh-szxYgTpG4tpt8UVun-8ajjczZ41LXEDUpXb2AQwynxBUrPyfYvn07MzmXaRKnoQyRq8ll1jy0xSNruJylSrB5YzbmmNO0Tm4bASu7pVpVutmrWPZnu8BVTSzl_DL5mrb_iAj7vqgbPC5fFI3W4zcVHDb5mW6WG7Z6R5pNhIkHw6i7LpaWzVxgj2Umv4t_q52cwbLIFG2JwQej0Z0Px32J7-p8Nd8geAIAR00whkSR7g=w854-h480-no)
And because of who I am I couldn't just add one function or style.
The one sitting different is the replacement for Trickster Bloom, with the similar but darker one working in inverse to it.
The one with redstone connected grants a speed buff depending on the power applied
The Spikey black one hurts like cactus and applies a short slowness debuff
The one up front can be recolored like my other colored blocks (4096 colors)
[side note: after adding this block I updated my other colored blocks, and rgb16 classes to make things more uniform]

![Identity Crisis.png](https://lh3.googleusercontent.com/qrQMmirzAgjdnrV3Z3yoFxOZZoQwEBf8JMFSPlVp9k_HAv2u_osXM7nEeg9pllcOiVjxuFYYIQTWR5RKihfecnh3aMwTpup0FRefjH7Jv8isJCAoQIN56woj0VWXE-kA6TVP73tx7e2R1CwyuDP8JRqOuPvtWPNqX7HDsOfd5NoOF6wG3mf0kZraBnpj-x2G-BgE0cOzjJo-EnqrJTPLP9VXqe-_6OwVHyQXsDWrchc86UMDnEVT-xBJplf1paTeeEzoEWIcUztRaEEkwaAB-A6f3B5_LD8DMRRWFDBCZHWsNXRSDMpPQMk7vzSlsbymIvu9Q3X4MVKve35XUikZ5gycd57ucXK0QqYR093pPnfFEoch28KUweKDsY5m_RgcooqQK3hxRuRky42Vk-NTVsOE7S53WjhZUq5Dd0qarsBaxTkK869SbbJf9kzBtDgQlrDi5sfcrmCP-CrO2ptqc3Gj0UWV76P4k2Wd9LY95jkNjEUrft1wM-tI046flB1ZcBltsU-kqY0hmizHVYgKpq-fdx-UuwNIW_lYC0WwQ301wWwBpH7g-eV490Pjus86He4hD_nsN9iQRUOX1HsaEnCxhNegc7bAtnyD2cA_zA=w854-h480-no)
I've dubbed this Identity Crisis.
The border on the right turns a neutral into a hostile, while the left turns a hostile into a neutral.
That poor mob doesn't know if its a wolf or a skeleton, but has the urge to gnaw on it own leg. :)

**Comment by ShetiPhian** [comment]
New builds have been uploaded to Curse

[ShetiPhianCore 1.11.0-3.4.8](https://minecraft.curseforge.com/projects/shetiphiancore/files/2493872)
[Terraqueous 1.11.0-1.3.16](https://minecraft.curseforge.com/projects/terraqueous/files/2493877)

[ShetiPhianCore 1.12.0-3.5.4](https://minecraft.curseforge.com/projects/shetiphiancore/files/2493873)
[Terraqueous 1.12.0-1.4.4](https://minecraft.curseforge.com/projects/terraqueous/files/2493878)

**Comment by VallenFrostweaver** [comment]
Sadly I can't see the images. It sounds like you've created a new kind of mob spawner option though. Thanks for looking into it.
