### ISSUE TITLE
[1.12][multi-storage] Ender chests set to team can't be broken

### ISSUE THREAD

**Issue by StarkRG** [ShetiPhian/Localizations-and-Issues#125]
I placed an Ender chest and put an emerald on it but now when I try to break it I get "only a team member can perform that action".  I can still access the chest, however. We've got FTB utils on our server and I'm the owner of the team.

**Comment by ShetiPhian** [comment]
This is due to the client being unaware of the team its on.
An issue I overlooked when I needed to add code to sync team display names (FTB stopped syncing the universe data, likely to save network traffic)

This requires an update to ShetiPhianCore
(to fix tooltip issues, EnderTanks and MultiStorage need an update also)

I have a test build for all three, just running them on a server now.

**Comment by ShetiPhian** [comment]
Here is the test builds
http://www.mediafire.com/?6dbe5477eb7el

**Comment by ShetiPhian** [comment]
Files have been uploaded to Curse.
