### ISSUE TITLE
[FTB Horizons III - Minecraft 1.12.2] Unable to make Power Pass blocks

### ISSUE THREAD

**Issue by FryoKnight** [ShetiPhian/Localizations-and-Issues#126]
This is most notable because there is no IC2, Buildcraft, EnderIO, Immersive Engineering, or TeslaCoils mods in the pack, only having Thermal Expansion/Dynamics, Xnet, and Integrated Dynamics for power transfer systems.

I ask that you add at least Thermal Expansion or Xnet in the config for being able to pour concrete to make RF Power Pass Blocks.

**Comment by ShetiPhian** [comment]
I haven't used Xnet or Integrated Dynamics, need to know how they move power before adding the Vault block.

While I can't seem to get power to flow through Xnet yet, I did figure out Integrated Dynamics. (didn't know Integrated Tunnels was required)

config > settings > vault > wallitems_caps
add: integratedtunnels:part_interface_energy_item

This will enable you to create a power pass with the Energy Interface from Integrated Tunnels.
Bit of a quirk though, 
You can't use an Energy Interface on both sides, you need to place a Battery on one before power can flow through the Power Pass.
This is due to the pass being coded as a hand off, but being unable to hand off access from one cable to another. It works with the battery though as the system sees it as being directly connected to the battery.

~~~
As for Thermal Dynamics, my RF Pass isn't being initialized so I'm looking at an API issue, likely need to update it.

**Comment by FryoKnight** [comment]
Thank you for looking into this, I will also provide this to the Server mods so they can update the config so that we can have access to power in our Vaults. ^-^

As for using Xnet cables, that would work out for my server, as most of the late game players use Xnet for a substantiate for EnderIO. I haven't personally played with it, but I know of it.

And if you are looking for a replacement for AE2, there is Refine Storage, it is heavily based on the original AE though.

**Comment by ShetiPhian** [comment]
Hold off on that, I'll be pushing an update today (very soon)

It fixes RF compatibility no longer working, adds the new defaults, and corrects wall pouring not working on game load (requiring a config reload)

**Comment by FryoKnight** [comment]
Cool, though we won't see the fixes until the next official release update of Horizons 3. XD

But once again, thank you for swiftly taking care of the issue. :3

**Comment by ShetiPhian** [comment]
I attempted to make the new version accept 1.4.6 clients, that way you can get away with only updating the server itself and leaving the clients on the older build until the pack updates.

Everything is handled server side, clients only need to know of the recipes. Horizons 3 uses the default configs so there is also no recipes the client needs.

But the 'acceptableRemoteVersions' function doesn't work, cant even pass * which should accept any version.

Without that working I had to resort to creating an imposter build (its 1.4.7 but reports as 1.4.6)
https://www.mediafire.com/file/bjmx38jxicsucld/multistorage-1.12.0-1.4.6%5B7%5D.jar

To use it:
  - delete: config/multistorage.cfg
  - delete: mods/multistorage-1.12.0-1.4.6.jar
  - add: mods/multistorage-1.12.0-1.4.6[7].jar

When the Horizons pack updates 'multistorage-1.12.0-1.4.6[7].jar' may need to be manually deleted
---

In 1.13 I'll be doing a bit of rework, when that is done I should be able to add xnet pass through (it requires a dirty hack now that may cause future problems), I'll also look into Refine Storage.
