### ISSUE TITLE
1.12.2 strange issue 

### ISSUE THREAD

**Issue by MadRatSRP** [ShetiPhian/Localizations-and-Issues#131]
[crash-2017-12-01_09.38.49-server.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/1520644/crash-2017-12-01_09.38.49-server.txt)

**Comment by ShetiPhian** [comment]
Its due to this recent Forge change:
https://github.com/MinecraftForge/MinecraftForge/pull/4549#event-1367056719

Its likely to be reverted/redone as changes that break binary compatibility mid version are normally rejected, and the odd time that get pulled they a reverted shortly after.

Just go back a Forge version for now.

**Comment by MadRatSRP** [comment]
Thank you.

**Comment by ShetiPhian** [comment]
Forge build 2558 fixed the binary compatibility.
