### ISSUE TITLE
Random Tesselating Crash

### ISSUE THREAD

**Issue by Akitori** [ShetiPhian/Localizations-and-Issues#133]
I ran out my base and got this weird crash from I'm assuming the Pagola fences. 

[crash-2017-12-02_17.15.27-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/1524346/crash-2017-12-02_17.15.27-client.txt)

**Comment by ShetiPhian** [comment]
This appears to be a random Minceraft derp.
While it was looping through 'addedTileEntityList' the list size changed. Likely another thread updating the tile entities within and clearing the list.

**Comment by ShetiPhian** [comment]
Thinking about this some more, 

This would happen when the render thread is getting a tile entity that is on a previously unloaded chunk border that has just been loaded, and finishes loading before the tile entity is returned.

Which would never happen in vanilla as it only happens when a tile entity renderer depends on information form a neighboring tile entity.

To fix this I'd need to pull fences, stairs , and gates out into their own blocks, but currently there isn't a way to map subblock to block. Making changes now would delete every one, block and item, currently in world.

In 1.13 however due to "The Flattening" it is possible to break up sub blocks, which I planned to do but now have an even better reason to do so.
