### ISSUE TITLE
[Platforms] Crash on world load while tesselating block model.

### ISSUE THREAD

**Issue by maham** [ShetiPhian/Localizations-and-Issues#144]
Crash to desktop after a block breaker broke a log. After this the world won't load because of a NPE while tesselating a block model (as far as I can tell from the log). Second time this happens. I'm able to delete the block in MCE and then the world loads fine.

Versions
---------
Minecraft: 1.12.2
Forge: 14.23.2.2611
ShetiPhian: 1.12.0-2.5.6
Platforms: 1.12.0-1.4.3b

Pastebin
---------
https://pastebin.com/iPKGE5F2

**Comment by ShetiPhian** [comment]
It appears the model couldn't be retrieved form the ModelLoaderRegistry.
Not sure if this is due to rendering happening before load (shouldn't be possible) or if I've typo'ed a name and the code if trying to get a model that doesn't exist. (but that should be causing an error any time a specific platform is used, not during an interaction between two blocks unrelated to mine)

Do you happen to still have a copy of the broken world? or can you cause the issue in 1.4.3b again?

If the error is from being unable to fetch the model this build should fix the crash:
http://www.mediafire.com/file/wu4q7tz6abqzy4m/platforms-1.12.0-1.4.4-TESTER.jar

**Comment by maham** [comment]
I found a backup of the world and it's consistently crashing on load. I'll try the supplied jar out and report back.

**Comment by ShetiPhian** [comment]
Uploaded to Curse
https://minecraft.curseforge.com/projects/platforms/files/2533246
