### ISSUE TITLE
Malisis Support (1.13)

### ISSUE THREAD

**Issue by kenijey** [ShetiPhian/Localizations-and-Issues#146]
Hi Shetiphian :3 can you add malisis doors support for your doors please? thanks :3 
https://github.com/Ordinastie/MalisisDoors/issues/221

**Comment by ShetiPhian** [comment]
Doesn't look like I can until 1.13

It looks like its one door per block/item
https://github.com/Ordinastie/MalisisDoors/blob/c2bba4f4d3da2b7b776cecf4be1f6a714a72679f/src/main/java/net/malisis/doors/DoorDescriptor.java#L401

All my doors share the same block (with other stuff) and use blockstates/meta

In 1.13 meta is gone, and block id's are basically unlimited (the map is stored per chunk, rather then per world, and there is enough id's that each block in a chunk can be unique)

Due to these changes Mojang will be unmerging their blocks (The Flattening) and I'll be doing the same.

**Comment by kenijey** [comment]
hmm.. thanks for the work and reply. we will be waiting for/in 1.13!
