### ISSUE TITLE
dense stone junkbox won't stack

### ISSUE THREAD

**Issue by mabelrxu** [ShetiPhian/Localizations-and-Issues#153]
stacking the stone junkboxes works fine for the not upgraded version, but once upgraded the dense ones won't stack. tooltip says capacity can be upgraded by stacking a second chest and/or using an upgrade, so stacking 2 upgraded ones should work

Multi-Storage 1.12.0-1.4.7 in Modern Skyblock 2 modpack

**Comment by ShetiPhian** [comment]
This one is rather counter-intuitive,
You stack a normal one with a dense one. (or stack two normal ones and use the upgrade item)

This was done to stop material loss in one case and duping in another.
If you stack two normal chests and use the upgrade, total materials are two Chests and one Upgrade.
Stacking two dense chests, total materials are two Chests and two Upgrades.

Both final blocks are the same, so what do I give when broken?
If I return two dense, scenario one results in a dupe, but if I only give back a normal and a dense, scenario two results in a loss.

.... Typing that out made me realize I should have just returned the extra upgrade item, likely one of my late night code sessions and due to it working I never revisited it. -_-

**Comment by mabelrxu** [comment]
:D

**Comment by ShetiPhian** [comment]
Working with junkboxes should be better in this build:
http://www.mediafire.com/file/1xufk01zibrzpwm/multistorage-1.12.0-1.4.9-TESTER.jar

Old code had:
Junkbox + Upgrade = Dense Junkbox
Junkbox + Junkbox = Double Junkbox
Double Junkbox + Upgrade = Dense Double Junkbox
Dense Junkbox + Junkbox = Dense Double Junkbox

New code adds:
Junkbox + Dense Junkbox = Dense Double Junkbox
Dense Junkbox + Dense Junkbox = Dense Double Junkbox (with an upgrade returned)

**Comment by ShetiPhian** [comment]
Uploaded to Curse
https://minecraft.curseforge.com/projects/multistorage/files/2537401
