### ISSUE TITLE
[1.12.2] Possible Chickens/Terraqueous Feather Spewing Issue

### ISSUE THREAD

**Issue by MokahTGS** [ShetiPhian/Localizations-and-Issues#154]
There is an issue that happens with Chickens where the babies spew feathers at a crazy fast rate.  This seems to happen when Terraqueous is present with the Chickens mod.  Turning off chicken drops in the Terraqueous config seems to have halted it however.

Is there anything in your code that could be causing this?

https://github.com/setycz/ChickensMod/issues/117#issuecomment-368339806

**Comment by ShetiPhian** [comment]
In LivingUpdateEvent I check the variable timeUntilNextEgg and base the drop chance on that.

Here are the four vales that can trigger a drop and the chance it will happen.
12000 = 100%  << this one isn't possible in vanilla as the range is 0-11999
9000 = 50%
6000 = 25%
3000 = 12.5%

My guess is the ChickensMod is setting the variable to 12000, and since I didn't exclude children (or jockeys), your getting 20 feathers per second per chicken.

I'll need to fix that, for now best to leave that option off.

**Comment by GenDeathrow** [comment]
Yes chickens mod increases the time for a chicken to drop its items way past vanilla chickens. The chicken drop time is based on the tier of the chicken (its all dynamic). But yes excluding children will more than likely fix the issue.

**Comment by ShetiPhian** [comment]
Well unless 4am is messing with me this code should be better then my existing.
Children and Jockeys have a 25% chance every ~2.5min [every 3k ticks existed]
Otherwise the chance is 25%, 50%, and 75% based on egg lay time. [3k=25, 6k=50, 9k=75, 12k=25, 15k=50, and so on]

http://www.mediafire.com/file/etnxwi6b6n85fgx/terraqueous-1.12.0-1.4.10-TESTER2.jar

**Comment by ShetiPhian** [comment]
New version uploaded to Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2537386

**Comment by GenDeathrow** [comment]
Man Glad we were able to figure this all out. This has been an issue for a long time, and we couldn't figure it out. Thanks @ShetiPhian @MokahTGS

**Comment by joernott** [comment]
@ShetiPhian, @GenDeathrow: I am running terraqueous-1.4.12 together with chickens-6.1.0, morechickens-3.2.0 and hatchery-2.1.2 and encountered that problem, too. Turning off feather spawning in terraqueous solved the problem for me as well, also does putting the babies into a nesting pen until they grow up.
