### ISSUE TITLE
Terraqueous: Furnace & Hopper

### ISSUE THREAD

**Issue by Gunvaldfar** [ShetiPhian/Localizations-and-Issues#16]
Hi,

I can not get out the ingots placing a hopper at the bottom of the furnace.
MC 1.10.2
gorge 2185
TQ: latest

**Comment by ShetiPhian** [comment]
Wow that bug is bigger then it appears.
The error is in my sided rotation handler, it doesn't exempt the top or bottom from being processed.

Block Facing:
North -- top and bottom handlers get swapped
East/West -- Crash
South -- Works Correctly

I'm currently back porting changes I made in my 1.11 builds into 1.10.
I'll try to get a new build of ShetiPhianCore out by the weekend.
Until then it will working by swapping the top and bottom configurations, or rotating the block to face south (remove hopper first or you'll crash and be unabe to get back into the world until the core is updated)

**Comment by ShetiPhian** [comment]
New build is up on Curse now.
