### ISSUE TITLE
ShetiPhian Core and Svarka

### ISSUE THREAD

**Issue by afanofjapan** [ShetiPhian/Localizations-and-Issues#171]
Got a crash from ShetiPhian Core when using Svarka. Some people are saying your core is using client classes. If you have Discord we can discuss this issue further. Log: https://pastebin.com/Qn52A2iw

**Comment by afanofjapan** [comment]
I am on Minecraft 1.10.2 by the way.

**Comment by ShetiPhian** [comment]
1.10 builds haven't been supported for a while now;

"shetiphian.core.asm.ClassTransformer:transform:58" is an output line to print why the ASM failed
"java.lang.ClassNotFoundException: net.minecraft.world.Teleporter" is not correct, that class is not touched at all, only Entity.createRunningParticles is altered.

If you want to see the code: https://gist.github.com/ShetiPhian/a00a9e8cb6e1e5cb6ec6deeb77400e68

Since the ASM code has been the same since 1.9, and working with Forge, its likely an incompatibility with Svarka.

You should be able to disable the ASM by, deleting the meta.inf folder form the jar, or the manifest.mf file within, or edit the file removing the two FMLCorePlugin lines.
