### ISSUE TITLE
Crash when joining a world

### ISSUE THREAD

**Issue by modmuss50** [ShetiPhian/Localizations-and-Issues#2]
https://gist.github.com/modmuss50/2cd96bfa1bdeebb78db16f1e2d11d13d

**How to reproduce:**
Login to server

Version: `1.2.7`

**Comment by ShetiPhian** [comment]
Something is causing the block to render before the tile entity packet arrives which contains the needed information to correctly render.
I was going to blame CodeChickenLib due to CCExtendedBlockRendererDispatcher being in the log's stacktrace, but I couldn't reproduce the crash even with it installed.

Regardless of what caused the race condition, I'll add some fallback defaults.

**Comment by modmuss50** [comment]
Ah nice, thanks.

**Comment by ShetiPhian** [comment]
I emulated the bug by postponing the client from updating the data.

This build should fix it, when the data is missing the door doesn't render, and when the  packet arrives I force a render update for the block.

http://www.mediafire.com/file/t69uajx50jeby43/multistorage-1.10.0-1.2.8-test_build.jar

**Comment by modmuss50** [comment]
Ah nice I will test it

**Comment by modmuss50** [comment]
That fixed the issue, thanks 👍

**Comment by ShetiPhian** [comment]
The only thing missing from that jar and the one I'll be uploading to Curse is the zh_CN.lang file, so if you want you can just remove the "-test_build" from the name.
