### ISSUE TITLE
Terraqueous flower quantities

### ISSUE THREAD

**Issue by xenoflot** [ShetiPhian/Localizations-and-Issues#20]
Hi,

I notice via TheOneProbe that there's an ever-changing value on Terraqueous's flower clumps. It seems to be the number of single-flowers one gets when breaking a clump.

Is this randomness done client-side or is information being sent to/from the server? 

Cheers!

**Comment by ShetiPhian** [comment]
I don't remember TOP displaying stacksize dropped...

Anyhow to the question;
The server picks a value between 1 and 3 when the flower is broken and gives that many singles.
I believe TOP uses getPickBlock server side and sends the stack info to the client.
Since I didn't override that method it will be returning the default, which is likely using the method I'm returning a random in.

When I can I'll look into cleaning up that display.

**Comment by xenoflot** [comment]
This is what I'm seeing http://i.imgur.com/4TsbrfV.png
terraqueous-1.10.0-1.2.14
shetiphiancore-1.10.0-3.3.6
mcjtylib-1.1x-2.3.1
theoneprobe-1.10-1.3.3
topaddons-1.10.2-0.9.0

Yes, I figured that the number would be selected server-side in response to a breakblock action. I'm just concerned that the constantly changing numbers suggest a constant information flow between server and client, generating unnecessary computation and data transfer. It's a small thing but it all adds up.

I may be worrying about nothing but I'll report to McJty as well.

**Comment by ShetiPhian** [comment]
I wouldn't be concerned, Minecraft sends a lot of data already and if the packet was large enough to become a performance hit McJty would have cached it.
The changing stacksize would break the caching though as it would be different then the last check and therefore synced.

**Comment by ShetiPhian** [comment]
New version was just uploaded.

**Comment by xenoflot** [comment]
Fabbo. I'll be updating the pack this w/e.

Cheers!
