### ISSUE TITLE
Terraqeous and Astral Sorcery

### ISSUE THREAD

**Issue by VeselchakAndrew** [ShetiPhian/Localizations-and-Issues#200]
The author of AS said that the error perhaps in Terraqeous 

--  "Not AS at fault. Perhaps terraqeous since it is also in the stack."

The altar don't drop after breaking with pickaxe

Log file:
https://pastebin.com/2N3BmCun
--

**Comment by ShetiPhian** [comment]
It appears your running an older build of Terraqeous as the line numbers do not match up.
A few versions ago I rewrote the block break handler due to the code added to support mod glass had issues in some mods.

You can disable the code block with this option:
Config > Tweaks > GlassShards > enableGlassShardDropsForBlocks

If your on the newest build or still have issues after updating to it, let me know as I may need to add an error handler for edge cases like this.

**Comment by VeselchakAndrew** [comment]
Thank You very much! Update the Terraqeous mod solve this problem!
