### ISSUE TITLE
[Request] Metal Platforms

### ISSUE THREAD

**Issue by Voxel-Friend** [ShetiPhian/Localizations-and-Issues#203]
Metal Platforms would be nice to have, as Currently I have to define custom blocks as either wood or stone, which is a bit strange when I make them out of steel or iron.

**Comment by ShetiPhian** [comment]
Metal are crafted with ingots.
There is no config option to add metals due to the ingot to block relation being cumbersome to represent. (The 1.13 configs may change this)

The Ore Dictionary is scanned for matching pairs of ingots and blocks, as long as there is both an ingot and block registered (eg. ingotTin & blockTin) the ingot will be usable.

If a mod registers both an ingot and block, they will be linked, otherwise the ingot will be linked to the first matching block entry.
