### ISSUE TITLE
Dynamic block support

### ISSUE THREAD

**Issue by TheDeviantCrafter** [ShetiPhian/Localizations-and-Issues#219]
Platforms supports only vanilla blocks by default. Although there's a config for adding new blocks, the vast majority of end users will never touch this config.

Most players don't tweak configs, and pack devs can't reasonably add every block their players may want to turn into a platform.

Mods like Little Tiles have out-of-the-box support for every solid block in the game.

**Comment by ShetiPhian** [comment]
It already is dynamic.
By default Platforms uses the Forge Ore Dictionary ("plankWood", "stone", "cobblestone", "sandstone", and pairs of ingot<Metal> block<Metal>) but more can be added via configs. (not metal variant though due to the ingot|block paring required)

Curse page about default blocks and ore dictionary:
https://www.curseforge.com/minecraft/mc-mods/platforms/pages/supported-blocks

Config Comment about custom entries:
By default Wood and Stone Platforms only use blocks registered to the Forge Ore Dictionary but additional blocks can be added here.
Format = modId:nameId@meta
modId can be left off for vanilla blocks, and 'ore' can be used to indicate a dictionary entry
nameId can contain [*] or [#-#] to replace an incrementing number or a number range
@meta can be left off to indicate any meta
