### ISSUE TITLE
[Request] Platforms: Disable Handrail Climbing

### ISSUE THREAD

**Issue by PickleWeaselPhD** [ShetiPhian/Localizations-and-Issues#223]
Could you please add an option to disable handrail climbing, either completely or per-placement? Handrails acting like ladders when I'm trying to ascend slopes or go around corners is frustrating. I wouldn't mind if none of the blocks were climbable, to be honest, but the behavior of handrails is the most frustrating.

**Comment by ShetiPhian** [comment]
Climbable rails was for convenience but there is always something off with the position that throws the logic and causes climbing glitches.

At one point I had no more false triggers, and they worked as intended, or at least I thought, turned out they would randomly no longer be ladders while climbing -_-

Minecraft just doesn't like a block that is a dynamic ladder.
I'll likely make only the Frame climbable and, provided no glitches, the platform on top.
