### ISSUE TITLE
Clouds spawn entirely black

### ISSUE THREAD

**Issue by Reshy** [ShetiPhian/Localizations-and-Issues#227]
![image](https://user-images.githubusercontent.com/2096384/72586408-795bb000-38a6-11ea-8dd4-338bde3d1ab4.png)

As seen here, when a new cloud spawns, it's lighting never updates, leaving it completely dark until something is placed on it to update the lighting.

**Comment by ShetiPhian** [comment]
This is an issue I haven't seen since 1.12
For some reason the chunk doesn't relight, the only way I found to correct it 100% was to enable the relight flag on generation placement. Problem with that is it causes lag as each generated block causes the whole chunk to relight.

This is something I'll just leave as-is, on the plus side it appears to happen less and less in each new Minecraft version. Also once Forges new generation system is fully implemented it might be completely solved in  a later 1.16.2 build
