### ISSUE TITLE
MC 1.14.4 Lava Transfer Faild on Server Lava transmission is not possible 1.14.4

### ISSUE THREAD

**Issue by Lice2** [ShetiPhian/Localizations-and-Issues#231]
Hi
I am currently using your mod on our server. People would like to transfer the lava from the nether with the refined storage system with your tanks, but somehow that doesn't work.
And another question how do you get the liquid from the tank?

Forge : 1.14.4-forge-28.1.117
MineCraft Version 1.14.4

**Comment by ShetiPhian** [comment]
Without other mods, regular bucks and linked (same color code and network) ender buckets are the only way to move fluids in and out of tanks.

I'm not good with the workings of most other mods, it been a very long time since I've actually played a pack.
I played around with Refined Storage, and have managed to get it to work. 

Looks like the importer and exporter are items only, and the Fluid Interface is the only block that can interact with tanks. (you likely already knew this, but I'm just discovering)

The interface requires fluids to be pushed or pulled, so to make it work with the tanks you need to use redstone to activate their internal pump, and have the interface on the correct face for the action wanted (top = fluid to tank, bottom = fluid to interface)
Tanks can be rotated, but not with the wrench in RS due to a compatibility glitch. For now break and place as tanks orientate their bottom to the block face clicked.

**Comment by Lice2** [comment]
Ok thanks I will test it.

**Comment by ShetiPhian** [comment]
A new build is available with a few fixes, including being able rotate with the refined storage wrench (sneak-click)

https://www.curseforge.com/minecraft/mc-mods/endertanks/files/2887774
