### ISSUE TITLE
[1.12.2] [Crash] [Compatibility] Issue with Tick Dynamic

### ISSUE THREAD

**Issue by aevumdefluo** [ShetiPhian/Localizations-and-Issues#232]
There is no crash log but it is in the log. Random crash due to tick dynamic interacting with terraqueous doodads.

Log:
[latest.log](https://github.com/ShetiPhian/Localizations-and-Issues/files/4242480/latest.log)

**Comment by ShetiPhian** [comment]
Doodad tiles do not tick, for that matter most of my tiles do not.
The log only has many entries of Tick Dynamic trying to remove tile entities form some list and failing. (my guess it its the list of tickable tile entities)
I'm not even the only mod with "Failed to remove" entries, just the most due to doodads being everywhere.

Without a stack trace from a crash I have not way of knowing what is happening.
It might have something to do with the frequent logging, you can try disabling them in their config.

Other then that I can't help with the limited information I have to go by.
I'm going to close this, but if you find out anything I can help with just post again.
