### ISSUE TITLE
[Bug] Burnium Ore & Mango trees/wood appear to have missing textures.

### ISSUE THREAD

**Issue by Mysteriaa** [ShetiPhian/Localizations-and-Issues#245]
See images. I'm using Forge for 1.15.2 along with Optifine.

![image](https://user-images.githubusercontent.com/67705660/89720680-d635c980-d9a2-11ea-8b37-af4e99ff054c.png)
![image](https://user-images.githubusercontent.com/67705660/89942770-2737fe80-dbeb-11ea-9383-c0ce301d830e.png)
![image](https://user-images.githubusercontent.com/67705660/89943654-8e09e780-dbec-11ea-8644-32c05952a687.png)

**Comment by ShetiPhian** [comment]
Invisible faces on the wood blocks was do to an x-ray bug my leaves had in the previous build (fixed in recent release)

The leaves being invisible and the Burnium having no textures would be an issue with Optifine and my MultiLayerModel. (you'll see Endimium Ore broken also)

My MultiLayerModel is based off of Forges, with additional support for fast/fancy mode model selection.
Optifine has likely broken Forges also, so when they fix that mine should be also working correctly.

**Comment by ShetiPhian** [comment]
My ores actually use forges model, so its not just mine that is broken.
You'll need to report the issue to Optifine

In 1.15.2 they cause _"forge:multi-layer"_ and _"terraqueous:multi-layer"_ to not render at all
In 1.16 they fixed _"forge:multi-layer"_ but now _"terraqueous:multi-layer"_, _"platforms:platform"_, _"multibeds:bed"_, and _"multibeds:ladder"_ display the missing model.

If they special cased forges they'll need to do the same for mine. In either case empty lists of baked models need to render nothing rather then using the missing model.

**Comment by ShetiPhian** [comment]
After further experimentation I found OptiFine did not fix forge:multi-layer in 1.16
Rather Forge inadvertently fixed it while working around the breaking change Mojang did to render layers in 1.16.

So the bad news is its not likely to be fixed by either Forge or OptiFine, as its not Forges issue and OptiFine doesn't appear to continue working on old versions of Minecraft.
But there is good news also, I know and have tested a fix I can implement. By back porting the 1.16 changes I can make my loader function normally thus fixing the invisible leaves, and changing my other blocks from Forges loader to my own will fix the purple and black cubes.

**Comment by ShetiPhian** [comment]
Terraqueous 1.15-1.6.2
https://www.curseforge.com/minecraft/mc-mods/terraqueous/files/3042292
