### ISSUE TITLE
Coconut madness!

### ISSUE THREAD

**Issue by xenoflot** [ShetiPhian/Localizations-and-Issues#25]
Hi,

I planted 3 coconut trees in my base, let them grow and cut them down a few times. Then it was time to redevelop that end of the base, so they got cut down for the final time.

Despite the lack of coconut trees, I'm still getting coconuts spawning on flat surfaces in that area!

I have "fruitStaysOnTrees=true". 

terraqueous 1.10.2-1.4.16.133
shetiphiancore 1.10.0-3.3.6

Cheers!

**Comment by ShetiPhian** [comment]
Only the coconut tree leaves do the spawning, each tree has 4 spawn spots each can have 2 coconuts growing.
fruitStaysOnTrees stops them from falling and in turn forces the tree to cap out at 8.

Coconuts start off as just a speck and will not fall until fully grown. After a while of sitting on the ground they change from entities into items which will despawn like any regular item.

After all the leaves are gone spawning will stop.

fruitStaysOnTrees does cause a side effect though, because the coconuts never drop you end up with them just floating there even after the leaves are gone. One would need to punch each of them. I'll need to correct this.

**Comment by xenoflot** [comment]
OK that explains it. I broke the leaf blocks with VeinMiner so I guess the spawning nodes weren't cleared.
What I was experiencing was unripe coconuts visibly on the ground. When I'd punch them, they'd just disappear. Later, I noticed some floating in the air. When I punched those ones, I got an edible coconut.

BTW the trees look great and the wood contrasts nicely with dark oak!

Cheers!

**Comment by xenoflot** [comment]
Hi,

I'm still getting some phantom coconuts on the ground. I'm placing dirt blocks in the area I think the tree used to be (to overwrite the spawn nodes) but either I've managed to miss the one last stop, or it's surviving the dirt. Is there any way to clear these spawning nodes?

**Comment by ShetiPhian** [comment]
There are no spawn nodes, it all happens in the onTick method of the leaves.
Without leaves, in the correct layout, coconuts can not spawn.
--Spawning--
First the leaf checks where on the tree it is making sure its on of the four that should spawn coconuts.
Then checks if there is less then two coconut entities bellow it. Then it spawns the coconut.
--Coconut Lifespan--
The coconut spends several ticks hovering bellow the leaf block slowly getting bigger.
If fruitStaysOnTrees is true, nothing else happens, if its false the coconut falls to the ground. About five minutes after falling the entity will change into an item, and that will despawn like normal.
NOTE: coconuts that have been placed will not despawn

I can't see another mod mistakenly adding coconuts to biome spawn tables, it is an Entity but not an EntityLiving.
Minecraft has glitched in the past causing some entities to be invisible, but that is fixed by logging out and back in again.

If for some reason there are invisible coconut entities, stand where your trees where and run this command.
/kill @e[type=terraqueous:coconut,r=64]
Note: this will not remove coconut items but they will self despawn just like any other item

**Comment by xenoflot** [comment]
Thanks for the comprehensive reply.

What I was experiencing was phantom coconuts appearing on the ground. There were no visible leaf blocks but some coconuts were appeared in the air as well. After popping the floating ones, the number of phantoms decreased. I plonked lots of dirt around and it cut the phantoms down to just one. 

If it was a simple server-desynch I'd expect relogging to show up the leaf block as you suggest, but nothing did. Also I've been flying around the base doing a lot of building and never once bumped into an invisible block. The phantom coconuts persisted over several reboots.

I have since plonked a lot more dirt around and it seems to have taken care of that last one. May as well ignore this for now, but if it starts popping up again, this information may be useful I guess.

I broke the leaves using an Actually Additions drill and VeinMiner. 

Relevant mods:
actuallyadditions-1.10.2-r97
fastleafdecay-v11
shetiphiancore-1.10.0-3.3.6
terraqueous-1.10.0-1.2.15
veinminer-1.9-0.35.3.595

Cheers!

**Comment by xenoflot** [comment]
OK so I had one phantom coconut so I ran your command. Apparently the syntax was wrong because it killed every entity on the server :-P Coconut seems gone, at least for now!

**Comment by ShetiPhian** [comment]
I tested that command before sending it, and again just now.
Only the coconuts should have been removed.

**/kill** by itself kills every entity including players.
**@e[]** indicates you want to apply restrictions to the command
**type=terraqueous:coconut** tells exactly what entity you want to kill, if it doesn't exist you'll get an error telling you the entity doesn't exist.
**r=64** restricts the kill commands area of effect to 64 blocks around the player using the command.

**Comment by xenoflot** [comment]
Just tried it 3 more times, triple-checked syntax twice and simply copy-pasted the third time. Kersplat each time. Apparently I'm special :-D Not to worry!
