### ISSUE TITLE
[1.16.2] Trouble walking up/down on ramps

### ISSUE THREAD

**Issue by WhitePhant0m** [ShetiPhian/Localizations-and-Issues#261]
[![Image from Gyazo](https://i.gyazo.com/4a5f52dea99df95a3bb947226cb27790.gif)](https://gyazo.com/4a5f52dea99df95a3bb947226cb27790)
Link above shows me having trouble walking up/down on ramps

platforms-1.16-1.7.3.jar
shetiphiancore-1.16-3.8.1.jar
forge 33.0.37

**Comment by ShetiPhian** [comment]
Collision boxes and selection boxes are loaded the same, and your selection boxes are correct.
Are you on a server? That would explain how the two can be in different load states.

Either way I couldn't get it to do this normally, but deliberately breaking the server side collision box load did simulate the video.
So for some reason the server side is not loading the collision data, so the game is using the fall back shape.
The last time I saw a similar bug, it was due to a race condition, causing the server to load the data too late, resulting is empty data being cached. That was fixed by not cashing empty data, and returning a fall back shape, which gets replaced when the data loads.
In your world, the data is never loading causing the temporary shape to always be used server side, and because it doesn't match what the client has the players position de-syncs.

I might just have to scrap that subsystem and just hardcode all the values.

**Comment by WhitePhant0m** [comment]
Yes, it's on a server

**Comment by ShetiPhian** [comment]
I've removed the resourced loaded collision data and hard coded the values. (lucked out too, the method I needed in my core was already public so the fix doesn't require a core update also)

This should finally squash that bug once and for all, but let me know either way.
Test build: http://www.mediafire.com/file/k0qd8omofz6hsvf/file

**Comment by WhitePhant0m** [comment]
That seems to have fixed it

**Comment by ShetiPhian** [comment]
Fixed builds are on Curse: https://www.curseforge.com/minecraft/mc-mods/platforms/files

Though this bug has only ever been reported on Platforms, the system is used in my other mods and if it fails to correctly load for one it bound to error on the others at some point. So I'll be removing it from them as well.
