### ISSUE TITLE
Suggestion - Split out Cloud/Storm

### ISSUE THREAD

**Issue by qodeninja** [ShetiPhian/Localizations-and-Issues#265]
I feel like this package is getting a little big, and I personally have no desire for any of the plant stuff -- just the cloud stuff. It would be great if you could split these into smaller mods.

**Comment by ShetiPhian** [comment]
While things do get split out to create new mods (MultiStorage, MultiBeds, and Platforms) this only happens when a feature is large enough to be its own thing.

Terraqueous is my world altering mod so its unlikely clouds will ever be split off.
But I keep it quite configurable. Each generator can be disabled, so it you do not want something its possible to turn it off.

(note this issue is only being closed to remove it from the main page, it is not locked and can still be responded to)
