### ISSUE TITLE
No Trees?

### ISSUE THREAD

**Issue by ThatTLeef** [ShetiPhian/Localizations-and-Issues#266]
I find that whenever I add Terraqueous into my mods folder, any world that I create never has any natural-spawning trees besides the one or two that spawn in village structures sometimes. I'm really not to sure what other mods it's clashing with because I've tried removing Tree Harvester and that isn't it. If anyone has had any similar issue or knows what this problem is caused by, please let me know if you know how to fix it! I'm running 1.16.2 with the mod version 1.7.2. If you'd like a mod list, could sometime tell me how to paste them somewhere? Pastebin isn't working for me. Thank you!

**Comment by ShetiPhian** [comment]
No trees, grass, or flowers, and none of my generation.
The biome decorator aborted due to errors.
Only saw this with OptiFine builds after pre2, but the hd_u_g3 build seemed to fix it.

1.16.2 has no proper way to add to world gen, the internal list has to be edited directly.

The only options currently available are, to disable my generators (option in the config file) or to find the other incompatible mod and decide which of the two you want and remove the other (also possible their generator could be disabled if unneeded)

**Comment by ThatTLeef** [comment]
> No trees, grass, or flowers, and none of my generation.
> The biome decorator aborted due to errors.
> Only saw this with OptiFine builds after pre2, but the hd_u_g3 build seemed to fix it.
> 
> 1.16.2 has no proper way to add to world gen, the internal list has to be edited directly.
> 
> The only options currently available are, to disable my generators (option in the config file) or to find the other incompatible mod and decide which of the two you want and remove the other (also possible their generator could be disabled if unneeded)

As it turns out, it's OptiFine that's the problem. Not sure if I can fix this without just ditching Opti altogether.
