### ISSUE TITLE
[1.11] Crafting Bench crashes client when putting materials in and clicking

### ISSUE THREAD

**Issue by shortybsd** [ShetiPhian/Localizations-and-Issues#27]
Forge version 2199
shetiphiancore-1.11.0-3.4.1
terraqueous-1.11.0-1.3.2

I placed down a Crafting Bench and put 4 planks to craft a crafting table, crashed my client with following error:

http://pastebin.com/ZrLN59aH

**Comment by ShetiPhian** [comment]
I didn't notice Forge has moved the firePlayerCraftingEvent from onTake to onCrafting.
Because I was overriding onTake and firing the event myself I didn't bother populating all the fields in the class. Now with the event moved its firing twice, and the one in onCrafting is reading empty variables causing the crash you see.

I'll need to set those fields and stop calling the event in onTake.

**Comment by shortybsd** [comment]
All good brother, I am still working on converting all my personal mods from 1.70 finally to 1.11/1.11.2. It is a pain and totally understand. I'll keep a watch for an updated version of your mod(s) :) Stay awesome!

**Comment by ShetiPhian** [comment]
Sorry for the delay,
I'm compiling now and will upload to Curse shortly

**Comment by shortybsd** [comment]
You are the man! Thank you sir.

**Comment by shortybsd** [comment]
Testing in 1 minute then closing issue.

**Comment by shortybsd** [comment]
Worked like a charm :) Thanks again
