### ISSUE TITLE
[bug] Crash on rotate of air block

### ISSUE THREAD

**Issue by hibikutek** [ShetiPhian/Localizations-and-Issues#274]
Minecraft Version 1.16.3
Forge Version: 34.1.25
Crash Report [here](https://pastebin.com/qREaXGam)

Steps to Reproduce:
Not exactly sure, I think it happened while using the monkey wrench to rotate a ramp with a rail attached.  I think if you rotate it too fast, then there might be a bit of a desync, and the wrench tries to do it on air, since the ramp hasn't been 'placed' yet.  This happens on a dedicated server.

**Comment by ShetiPhian** [comment]
I see the crash.
When a Ramp or Floor is rotated it also rotates the attached Handrail, the problem happens when the platform subtype is one that doesn't support a handrail thus the block is missing.

Checking for the block first fixes that, but another bug takes its place -_- the rail is getting deleted, need to figure out why.

Also found and fixed another rotation bug, rotating the attached rail itself causes it to become the block its attached too. (just a typo)

**Comment by ShetiPhian** [comment]
This should fix all the rotation bugs:
http://www.mediafire.com/file/d2joksergtx5aa2/platforms-1.16-1.7.7--TESTER.jar/file

**Comment by ShetiPhian** [comment]
New build is now on Curse:
https://www.curseforge.com/minecraft/mc-mods/platforms/files/3106977
