### ISSUE TITLE
better mekanism support

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [ShetiPhian/Localizations-and-Issues#283]
currently mekanism gas pipes wont connect to ender tanks, i think gasses in that mod are handled like liquids just through different pipes so it should work with your other existing code minus the patch to allow those pipes to connect... if i'm right.

**Comment by ShetiPhian** [comment]
While Mekanism Gas is similar its a completely different system then Fluids.
I'm not seeing a way to support it without rewriting much of the Storage code or without making the Mekanism api required.

**Comment by C4PTRAMPAGE** [comment]
well i was told thats how it worked, i guess the info was wrong.
i assume theres no way of using the api only if the mod is installed then... what about a config option that toggles use of the api? i dont know how much work i'm asking you to do so if you dont want to i'm not going to force the issue.

**Comment by ShetiPhian** [comment]
In a normal situation it can be implemented the same way liquids are, by having the tileentity return the needed object via getCapability. The problem comes from EnderTanks not storing the contents in the tileentity rather its in a database of FluidTanks, so the contents can be accessed by any tank or bucket.

This leaves me with two ways to solve this. Implement the needed classes on the database object, thus creating a hard dependency on the Mekanism api. Or change the way the database object works so it is no longer a fluid tank but an object holder which contains a fluid tank and optionally a Mekanism gas tank.

The first option is out for the same reasons I don't do it for any other api. I'd either have to make the other mod required or copy their api into my mod. If they change their api the game crashes or glitches until I update for the changes.

The second option allows gas support to be automatically enabled and disabled if the api exists, and allows for a config option to disable support if it is unwanted or causing issues. This does require a good amount of code changes, but is the best way to add support., and as a bonus once done supporting another mods tankable object would be much easier. (no others come to mind though)

**Comment by ShetiPhian** [comment]
I'm not too familiar with the mechanics of Mekanism, but it looks like tanks are functioning correctly.
https://www.mediafire.com/file/1288yg9vnf0y0xx/endertanks-1.16-1.9.4--TESTER1.jar/file

While buckets will only handle liquids like before, the tanks should work with liquids, gas, infusions, pigments, and slurries simultaneously.
To make tanks work with pushed based pipes like Mekanism uses, while the internal pump is active the top is restricted to input only while the bottom is restricted to output only. (while off both faces can still function as either input or output)

**Comment by C4PTRAMPAGE** [comment]
from what i can tell it works without issue, thanks!

**Comment by ShetiPhian** [comment]
Noticed the other day I hadn't uploaded these changes to Curse.
Have done so now though.
