### ISSUE TITLE
Missing Textures??

### ISSUE THREAD

**Issue by keepinitreal247** [ShetiPhian/Localizations-and-Issues#287]
Awesome mod btw the only problem I'm having is every so often the bed frame will turn into missing textures I don't know how it happens and it only seems to happen to double beds and its only the frame 

![2021-01-01_20 31 06](https://user-images.githubusercontent.com/72453022/103449633-6507f300-4c70-11eb-9c81-323b0ba37b76.png)

**Comment by ShetiPhian** [comment]
That's also not the correct models; its two singles when it should be a left and right.
All of that info is in the TileEntity, so is it missing data or rendering wrong...

Are the beds correct when placed? If so when do you notice they break?
Is this single player or a server?
Is the OneProbe window icon correct?
When you break the bed, is the item dropped correct? If so does placing it result in a correctly textured single bed?
What happens when you add a sheet, pillow, and blanket?

**Comment by keepinitreal247** [comment]
> Are the beds correct when placed? If so when do you notice they break?-Yes the beds are fine when placed both the texture of the block I choose and the beds are connected and the times vary from a few seconds to a couple of minutes I'm always running around so I don't really have an accurate reading
 
> Is this single player or a server?-It is a single-player world but I sometimes open to Lan so my brother can play

> Is the OneProbe window icon correct?-Yes it shows the texture of the block I choose and the design of the frame 

> When you break the bed, is the item dropped correct? If so does placing it result in a correctly textured single bed?- The item does drop and replacing it does fix it but only for a few seconds or mins

> What happens when you add a sheet, pillow, and blanket?- I haven't added any yet but I have had this bug happen before I just haven't been as bothered up until now and putting sheets on it doesn't fix it the frame is really the only thing bugging out

Thanks For Replying Btw

**Comment by ShetiPhian** [comment]
My best guess is the split TileEntity I used, to keep client only variables and functions separate, is interacting with another mod in a funny way (again), so I've rearranged code and a split tile is not used anymore (which I should have done that last time)

Here is a test build:
https://www.mediafire.com/file/n05z34lrb3suxbv/multibeds-1.16-1.7.7--TESTER1.jar/file

**Comment by keepinitreal247** [comment]
Right so I used it and it seems to be doing the same thing except both the double and the single seem to be doing it now I have a vid instead of a pic this time but it says it to big even when I zip it

**Comment by ShetiPhian** [comment]
Not due to the split tiles then.
What is causing the model data to be empty. Either it's getting erased or the tile data is, resulting in empty model data. And then the question becomes is it erroring while processing data or being fed invalid data.

Does it happen in a fresh world? what about with no other mods?
With no error to go by I'll need the save folder, along with the mods and configs (if its a mod pack, I just need the name and a list of any changes you've made)

**Comment by keepinitreal247** [comment]
> Not due to the split tiles then.
> What is causing the model data to be empty. Either it's getting erased or the tile data is, resulting in empty model data. And then the question becomes is it erroring while processing data or being fed invalid data.
> 
> Does it happen in a fresh world? what about with no other mods?
> With no error to go by I'll need the save folder, along with the mods and configs (if its a mod pack, I just need the name and a list of any changes you've made)

(sorry getting all that will take a bit rn I'm having problems with the world buggin out the mods are freezing and chunks won't load in )

**Comment by keepinitreal247** [comment]
ok do it does happen in a new world with the other mods but doesn't without the other mods

 Debug-https://gist.github.com/keepinitreal247/63eb8908a572d3fa76bf679fd7f08919

How do I send the save and config folders it says it's too large?

**Comment by keepinitreal247** [comment]
ok do it does happen in a new world with the other mods but doesn't without the other mods

Debug-https://gist.github.com/keepinitreal247/63eb8908a572d3fa76bf679fd7f08919

How do I send the save and config folders it says it's too large even when I zip it?

**Comment by ShetiPhian** [comment]
I think a free MediaFire account will handle the file.
