### ISSUE TITLE
MultiBed CRASH

### ISSUE THREAD

**Issue by iobiarg** [ShetiPhian/Localizations-and-Issues#292]
Hi there, ussing multibeds pretty fine up to now...
I tried to use the threading kit on the blanket of a bed... instant freeze and a crash that didnt generate a crash report to post.

**Comment by ShetiPhian** [comment]
One-off error or frequent?
the former is harder to nail down, and can be caused by any random thing (eg. bit-flip in ram)

Either way, the most recent crash report is needed.
The crash report file is often still created even if the game aborts without displaying the error.
If it didn't, it's possible the crash was written to the latest.log

**Comment by iobiarg** [comment]
Gave it another try, is a conflict with the thread and the shader or optifine... happens in the same situation, when trying to use the embroidery thread on a blanked on a bed.
Shaders give many errors, but seems to kill java with this item only.

[latest.log](https://github.com/ShetiPhian/Localizations-and-Issues/files/5977089/latest.log)

Anyhow, I'm right now downloading the new core and mod version.

**Comment by ShetiPhian** [comment]
Well I'm not in the stacktrace, and the gui doesn't do anything bizarre, so I've got no idea why opening it causes the shaders in world renderer to freak out.
But I see "optifine.render.VboRegion" in the log though, so I have an idea of a possible solution.

Make sure Optifine Render Regions is disabled (options > video settings > performance)
It has a nasty habit of throwing OpenGL errors, and apparently lacks checks and error handling.
