### ISSUE TITLE
Crash with RFTools Dimensions and Terraqueous tree generation

### ISSUE THREAD

**Issue by joral** [ShetiPhian/Localizations-and-Issues#3]
Playing on version 1.15 of the Avant 3 mod pack, plus RFTools Dimensions.  I created a new blank dimension tab, generated the world, and jumped to it.  It looked like world gen was attempted, but it failed.  It also fails every time I attempt to log in.

http://pastebin.com/DcZYAEF6

**Comment by ShetiPhian** [comment]
Looks like you where shutdown by the Server Watchdog. This happens when one of the game threads stall for too long.

Something is likely wrong with the world itself.

shetiphian.terraqueous.common.worldgen.GenTrees.generateTree(GenTrees.java:136)
is a call to world.isAirBlock(pos), if there was something wrong with either the world or pos variables the crash would have happened sooner and wouldn't have been "java.lang.Error"

Other watchdog crashes where reported to Mojang and their recommendation is:
Set max-tick-time in server.properties to a value higher than 60000 or to -1 to turn it off.
max-tick-time=100000 and running the server without the gui is suggested by other users

**Comment by joral** [comment]
I could try that.  As a test, I removed terraqueous, and tried again.  Apparently RFT dimensions was being horribly perverse and decided I needed a void world.  Not sure how this would affect your tree gen, but that's what we had in this case.  If it brings you any light...

**Comment by ShetiPhian** [comment]
It does;
While I didn't have issues with RFTool worlds, I never got a fully void world all had tendrils or spheres, but I can see a fully void world having issues.

getTopBlock scans down looking for a block (the only difference between the default and mine is I don't ignore liquids)
So in a void world this is 256 calls to world.isAirBlock
Now that is not to bad by itself but;
Doodads check four times, Flowers check once, Plants check once, Trees check once.
That is 7 checks per chunk, or 1792 blocks per chunk.

So I've gone back and made the changes I could.
- Split getRandomTopBlock into getRandomXZ and getTopBlock
- Re-arranged generators so the biome check is done before y-level scan
Those allow the processing heavy scan to be avoided if its not a valid biome, but doesn't help in void worlds that use normal biomes.
To fix that my generators now fire and check the DecorateBiomeEvent, as void worlds should be canceling these.

Here is a test build:
http://www.mediafire.com/file/c3g6djt51zy1yn3/terraqueous-1.10.0-1.2.9-test_build.jar

**Comment by joral** [comment]
Thanks,
I will check it out and see what happens.  To be honest, I've deleted that dimension, and don't remember specifically which dimlet(s) I had specified, so I might not be able to generate the exact same thing again.

Will let you know how it goes.
