### ISSUE TITLE
Players unable to join server with setiphiancore present.

### ISSUE THREAD

**Issue by frikinjay** [ShetiPhian/Localizations-and-Issues#315]
**Describe the bug**
Players trying to join get kicked with the following message
![unknown (1)](https://user-images.githubusercontent.com/88995340/148708129-5ea67c7f-0ab0-46ce-a9c5-e162b8bafcc2.png)

**Additional context**
Minecraft Version: 1.18.1
Forge Version: Fabric 0.12.12
ShetiPhian Core Version: 1.2.0
My Mod(s) Name & Version: ??
Are other mods present?
If yes:
- Does everything work without my mods?
Yes
- Have you tested with only my mods?
No

PasteBin or GitHub Gists links
latest.log = https://pastebin.com/rPF7YZTL
debug.log =

**Comment by ShetiPhian** [comment]
The client message and the server error are different.
Maybe due to the missing registration something in the mappings get messed up.
Strangely in the development environment it doesn't kick the player, still logs the server error though.

Anyhow here is a test build with the missed command argument type registration.
https://www.mediafire.com/file/kvdekk1c5lj1xnp/shetiphiancore-%255Bfabric%255D-1.18-1.2.1--TESTER.jar/file

**Comment by frikinjay** [comment]
Thanks, i'll let you know if it persists.

**Comment by ShetiPhian** [comment]
This build was uploaded to Curse.
No need to redownload, If you wish you can rename removing '--TESTER'
