### ISSUE TITLE
Multibeds crashes with REI

### ISSUE THREAD

**Issue by Sunconure11** [ShetiPhian/Localizations-and-Issues#321]
https://github.com/shedaniel/RoughlyEnoughItems/issues/769

**Comment by Sunconure11** [comment]
Okay, this is strange, because I do have Indium

**Comment by ShetiPhian** [comment]
You'll need to roll back to alpha5 until Indium releases a new build.

[Sodium mc1.18-0.4.0-alpha5](https://www.curseforge.com/minecraft/mc-mods/sodium/files/3542074)
[Indium 1.0.2 for Minecraft 1.18.x/Sodium 0.4.0-alpha5](https://www.curseforge.com/minecraft/mc-mods/indium/files/3542434)

**Comment by Sunconure11** [comment]
Alright, will do so tomorrow. Didn’t get much sleep

**Comment by ShetiPhian** [comment]
I've let Indium know.
https://github.com/comp500/Indium/issues/100#issuecomment-1033159120

**Comment by ShetiPhian** [comment]
You can stick with current builds.
comp500 responded pointing out Indium is compatible, and I just tested it.

Either there is an issue with your Fabric-API jar or some other mod breaks Indium.
Launch with just:
- architectury
- cloth-config
- fabric-api
- indium
- multibeds
- roughlyenoughitems
- shetiphiancore
- sodium

If things do not work redownload.
If they do add mods back, with dependencies, in small groups, keeping track of what you add. When the issue returns remove what you just added and re-add one at a time.

**Comment by Sunconure11** [comment]
https://modrinth.com/mod/ebe

By any chance, could this be it?

**Comment by ShetiPhian** [comment]
Haven't had the chance to test it.
It sounds like it converts block entity rendering into regular block rendering. 
I can't see it being the cause because it also uses the Fabric Rendering API.
The quickest way to check though, is to temporally remove it and see if the crash still happens.


Side Note:
Future builds of my core will handle this render issue differently/better.
Rather then letting the game crash, or invoking a controlled crash with better details, it will log an error when rendering fails and the block will just be invisible.
