### ISSUE TITLE
Open source ?

### ISSUE THREAD

**Issue by liabri** [ShetiPhian/Localizations-and-Issues#333]
May I ask why none of your mods are open source ? It is quite frustrating to be honest, I personally only use mods that are open source so in the event that a mod becomes unmaintained (very likely to be honest, it is beyond normal for mod developers to stop maintaining mods) I can still keep it in my modpack which I update every other minecraft update. This allows me to keep everything consistent and personally maintainable. Many of your mods are great (MultiBeds being the ones that piques my interest most), I really think it would be a pity if your mods die or go unmaintained for a long period of time. Is there any way or time your mods' source code  will be released ?

**Comment by ShetiPhian** [comment]
I wasn't sure how detailed I wanted to answer. So I'll keep it rather short.
When I started I went closed source for personal reasons, (bad experiences, paranoia, etc.  and I'll leave it at that)
Open source isn't possible with the version control I'm using, and migrating to another would be a hassle and loss of history all for no tangible gain.
So there is no plans to go open source, but jd-gui does decompile well enough if your wanting to look it over.

**Comment by ShetiPhian** [comment]
Figured I should add some mod info/history.

Mod development is current & previous Minecraft version and bug fixes are applied to two versions back (though lately I have also backported features)

I've been around since 1.4 (I think the Bucket plugins where 1.3)
In that time three mods are not on 1.18

- Change-It; as someone else had made a far more capable one "MineTweaker" so it was discontinued in 1.5
- PixelPowers; This one was phased out, it grew beyond its initial scope and was broken up  into Terraqueous, MultiBeds, MultiStorage, and technically Platforms (though in internal builds only)
It never got it rewrite because the mod it was a companion to was discounted when its author left.
The magic system may be gone but its paintings are still part of the PixelPowers mod id, and included with Terraqueous (though disabled by default in the configs as not everyone wants MLP themed paintings)
- MultiStorage; Needed a complete overhaul, and got stuck in indecision.

**Comment by liabri** [comment]
I see, well I suppose I'll have some faith for this mod since it's so great (and you have a hell of a track record, damn good job!), but may I ask out of curiosity: in the event development for multibeds stops, is it possible that you'll dump the source code somewhere ?

**Comment by ShetiPhian** [comment]
Currently GitHub would be my choice. I've already got an account, and unless deleted by the owner projects appear to be archived permanently.
