### ISSUE TITLE
Feature Suggestion: Enderchests/Endertanks/ShetiphianCore - /spc_teams gui

### ISSUE THREAD

**Issue by GoliathX211** [ShetiPhian/Localizations-and-Issues#334]
I have been using your mods and are absolutely loving them. I just wanted to give a little feedback. I personally have had a few problems likely server related (on them not you) and I was just thinking about how FTBTeams has a very player-friendly UI that I would love to see developed with this mod. However you choose to do it is your choice and I don't want to specify too much but having an interface with the team that can show you all of the teams different recognized "team ender chests/tanks" with their upgrades and maybe even showing their real-time inventory would be absolutely wonderful.

I am going to try to add the label that the others have but idk if it is something I can do or know how to do.
Edit: I have no clue what I am doing, I apologize.

**Comment by ShetiPhian** [comment]
There is some GUIs I've just never gotten around to doing.

I wanted a way for you to see all chests and tanks on your personal or team networks that either had the capacity upgraded or contains something and display all information. That will help finding one you've used but have since changed the color bands.

A UI to set up teams would also be nicer then relying on commands only.


I thought by now I would have gotten at least something in, but maybe someone making a companion mod is more likely
Everything is server side only and sent to the client as needed so the UI would need to request data.
