### ISSUE TITLE
I cannot add my custom embroidery design to my bed.

### ISSUE THREAD

**Issue by MichikoYumi** [ShetiPhian/Localizations-and-Issues#337]
Hello, so I do have a blanket on the bed and I have been able to add other designs to the bed. The spool is not out of thread as I only tried 2 other designs on the bed. It is only when I try to add my own drawn design on my bed that it doesn't work. I have the dependency for multibeds downloaded. How do I get this issue fixed?

**Comment by ShetiPhian** [comment]
I'm not getting the issue, or at least not replicating the conditions for it to appear.
What versions are you using? (ShetiPhianCore, MultiBeds, Forge/Fabric)
Does it work with just my mods installed?

The two others that worked, where they both from the Embedded tab or was one of the Web Fetched ones also tested.
(Embedded ones work differently then all of the others as their images are included while the others are generated)

Try copying and saving one of the ones from Embedded or Web Fetched.
Can be applied from the Personal tab?

**Comment by MichikoYumi** [comment]
I am using ShetiPhianCore-1.18-3.10.5 , Multibeds-1.18-1.9.4 and forge for version 1.18.2 . It does work with only your mods installed. If you would like a list of the other mods I am using to make it more accessible or to probably find a conflicted issue I can attach them in another comment.

With the other mods installed, only the ones from the embedded tab were working. I tried to copy an embedded one and apply it, nothing happened. I tried to apply a web-fetched one, nothing happened. I tried to copy a web-fetched one and apply it, nothing happened.

Here is the list of the other mods I am using:
Advanced netherite, backpacked, catalogue, cfm, configured, crafting dead, curious api, geckolib, iron chest, JEI, journeymap, MCDoom, Macaw's Doors, Reliquary Reincarnated, trajan's tanks, villager tools, and the undergarden.

**Comment by ShetiPhian** [comment]
Because Embedded ones use image files they are rendered via the block model, but because the others are generated they are rendered via tile renderer.
You likely can't use banners as blankets either, as they are applied in the same renderer.

Actually the way Banners work is the basis of custom embroideries, do Banners render correctly? what about vanilla chests?
If neither render then tile rendering is broken, but if chests render and banners don't something is broken with generated images. (maps in frames use the same system also)
If those work, its possible they've been patched to work with the breaking change.

At least the mod list is short, I was expecting another 100+ pack.
JEI can be ruled out too, its in my runtime test instance.

At a glance only one stands out; Is cfm Crayfish's Furniture Mod?
I know it has some fancy rendering, its possible we have a Mixin conflict.

**Comment by ShetiPhian** [comment]
So just installing the mods does not break the renderer.
Its possible the mod has updated since you added it, and the newer version I ended up using corrected the issue.
More likely though the issue is when a block with an incompatible renderer is within render range of the bed.

To test that; with all the mods installed, try creating a new world with the void preset. Only place a bed with blanket, do the web-fetched work?
If that is the case the problematic block should be finable by picking stuff up around the bed until the renderer starts working.

**Comment by MichikoYumi** [comment]
[https://clips.twitch.tv/FancyGoldenTardigradePRChase-7aqaWCBuT8Hjdtm6](url) . I am playing on a multiplayer world with my boyfriend and the embroidery thread does not work there. However, going into a single player world and placing a bed down does work with all the above embroidery options (client, web fetched, and custom).

**Comment by ShetiPhian** [comment]
I've been looking for a mod conflict or rendering incompatibility, and its been my own dumb mistake.

When I added the project system, which is client only, I inadvertently caused an issue in my server packet. (it now references an unreachable method)

**Comment by ShetiPhian** [comment]
Test build took longer then expected; I had to wrap-up some changes to the core and implement backwards compatibility (wasn't expecting on another release before Forge left beta)

https://www.mediafire.com/file/t56z5qgzk4s1glf/multibeds-1.18-1.9.5--TESTER.jar/file
https://www.mediafire.com/file/bpkhhmr48nkvese/shetiphiancore-1.18-3.10.6--TESTER.jar/file

**Comment by RedNPanda** [comment]
Not working on 1.18.1 ![image](https://user-images.githubusercontent.com/97081955/160615686-4e5d61b5-ff2e-4a2b-8a05-34bac4d3720f.png)

**Comment by MichikoYumi** [comment]
I wish I could test this build on aternos, but the way aternos allows you to add mods is when the mod has been updated on curseforge. So there would be no way for me to test the test build on aternos until then.

**Comment by ShetiPhian** [comment]
@RedNPanda 
This is a 1.18.2 build, it will not work on, or be ported to, 1.18.1
I have one development environment per supported major Minecraft version. (currently 1.18, 1.17 & 1.16[bugfixes])
Code is kept compatible with as many minor versions as possible but Mojang broke compatibility between 1.18.1 and 1.18.2, so 1.18.1 is no longer supported.


@MichikoYumi 
No problem, though I generally prefer to get a fix verified by the reporter before upload, that's not always possible.
I was able to reproduce the issue on a server, and this fixed it there.
Once I get this ported to 1.17, 1.16, and Fabric I'll upload them all to Curse.

**Comment by ShetiPhian** [comment]
Builds are now on Curse

**Comment by MichikoYumi** [comment]
Booted up my Aternos server with the updated mod and dependency and it WORKED!
![2022-03-30_18 55 10](https://user-images.githubusercontent.com/25468568/160944314-e7d2976a-8158-4e10-a374-63d8601cfb0f.png)

**Comment by ShetiPhian** [comment]
Glad that solved it, sorry it took so long.
