### ISSUE TITLE
Incompatibility to Fixed Waterlogging

### ISSUE THREAD

**Issue by TheButterbrotMan** [ShetiPhian/Localizations-and-Issues#342]
**Describe the bug**
Crashing at start of client

Probably a incompatibility to https://www.curseforge.com/minecraft/mc-mods/fixed-waterlogging

**Additional context**
Minecraft Version: 1.18.2
Fabric Version: 0.13.3
ShetiPhian Core Version: 1.2.6
My Mod(s) Name & Version: MultiBeds 1.2.4
Are other mods present?
If yes:
- Does everything work without my mods?: Yes
- Have you tested with only my mods?: No

PasteBin or GitHub Gists links
latest.log = https://bytebin.lucko.me/L57FGZVnbe

**Comment by ShetiPhian** [comment]
Looks to be. Its adding the waterlogged property to the vanilla beds, which mine extend, so when I add it to mine the validation fails due to a duplicate.

The problem with the validator is its operating on the assumption that the exact same property wont be added twice, so its protecting from two different properties having the same name.

Give this build a try,  it has a Mixin that skips exact duplicate properties from being added, and the game loads with 'Fixed Waterlogging' now.
https://www.mediafire.com/file/jjjqjc3ins02eg9/shetiphiancore-%255Bfabric%255D-1.18-1.2.7--TESTER.jar/file

**Comment by ShetiPhian** [comment]
Curse updated
