### ISSUE TITLE
Clientcrash

### ISSUE THREAD

**Issue by TheButterbrotMan** [ShetiPhian/Localizations-and-Issues#360]
**Describe the bug**
It just crashed.

**Additional context**
Minecraft Version: 1.18.2
Fabric Version: 0.14.8
ShetiPhian Core Version: shetiphiancore-fabric-1.18-1.2.12
My Mod(s) Name & Version: https://www.curseforge.com/minecraft/modpacks/deathdusk
If yes:
- Does everything work without my mods? Yes
- Have you tested with only my mods? No

PasteBin or GitHub Gists links
latest.log = https://bytebin.lucko.me/J1txVD444C

**Comment by ShetiPhian** [comment]
In the client config file set 'enable_tooltip_line_wrapper' to false;


Looking things over it appears this crash should happen even without my code, but you tested without my mods.

TooltipComponent.of  only accepts either an OrderedText or a TooltipData
OrderedText is just wrapped (and If OrderedText was null it would crash in StringVisitable.visit with a NullPointerException)
TooltipData is checked if its an BundleTooltipData if not it throws an IllegalArgumentException with the same "Unknown TooltipComponent"

My guess is another mod is passing its own TooltipData, and is also hooking into Screen.renderTooltip. 
Normally they process it and have no issues, but since I'm also hooking the same method my code tries to, causing the vanilla check to fail because its not an instance of BundleTooltipData 

I do wonder what mod it is and what is being added, as it might be possible for them to hook TooltipComponent.of(TooltipData) instead and return a TooltipComponent.


I've changed my code a bit to handle this. Also added a new config option 'enable_tooltip_broken_notice'
Its disabled by default as its only useful for troubleshooting, when enabled it adds "<data error>" to the tooltip so items with issues can be found.
https://www.mediafire.com/file/19skdt2vd5590tz/shetiphiancore-fabric-1.18-1.2.13--TESTER.jar/file

**Comment by TheButterbrotMan** [comment]
I dont really know how to test it, because i dont know how to reproduce this crash.

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/bILOZPqHSX

**Comment by TheButterbrotMan** [comment]
Another one: https://bytebin.lucko.me/ftx93zXSt0

**Comment by ShetiPhian** [comment]
https://www.mediafire.com/file/8lb2fxmvzb2q8az/shetiphiancore-fabric-1.18-1.2.13--TESTER3.jar/file
This should solve the issue (EasyShulkerBoxes works)

**Comment by TheButterbrotMan** [comment]
When will this be uploaded on curseforge? I need to include this asap into my modpack.

**Comment by ShetiPhian** [comment]
Up now.

**Comment by TheButterbrotMan** [comment]
Thank you. Seems to be fixed!
