### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by lostopkk** [ShetiPhian/Localizations-and-Issues#366]
**Describe the bug**
Crash

**Additional context**
Minecraft Version: 1.19
Forge Version: 
ShetiPhian Core Version: 1.3.1

PasteBin or GitHub Gists links
latest.log = https://www.toptal.com/developers/hastebin/uxewopuxuq.properties
debug.log =

**Comment by lostopkk** [comment]
sorry, repo wrong

**Comment by lostopkk** [comment]
sorry, repo correct XD

**Comment by ShetiPhian** [comment]
Multibeds is the first crash but myrtrees, platforms, supplementaries, and transportables all crash trying to access class_1921 (RenderLayer)

Tempad has a failed mixin into class_757 due to the refMap missing (the mod didn't compile correctly)
(class_757 is GameRenderer, which is used by RenderPhase which is the class RenderLayer extends)

Try updating/downgrading/removing Tempad

**Comment by lostopkk** [comment]
solved, thanks!

**Comment by CodexAdrian** [comment]
Hello, just wanted to make a note that this issue should be fixed as of Tempad 1.4.1, and i apologize for any inconvenienced caused by Tempad.
