### ISSUE TITLE
unable to break ender tanks

### ISSUE THREAD

**Issue by aglarcz** [ShetiPhian/Localizations-and-Issues#374]
Unable to break any ender tanks on 1.12.2 server.

Minecraft Version: 1.12.2
Forge Version: 14.23.5.2860
ShetiPhian Core Version: 1.12.0-3.5.9
My Mod(s) Name & Version: Endertanks-1.12.0-1.6.8
Are other mods present? yes, bugs even without them

Error log: https://pastebin.com/raw/7rQyFRiq

**Comment by ShetiPhian** [comment]
I deleted my 1.12 development environment a while back because compile stopped working.

Though it won't be fixed I looked into the code for the issue, somehow the world variable must be null while your in world and its loaded, as that's the only value being used in the line that crashed.
```
public FluidTank getTank()
{
    return TankHelper.getTank(getOwnerID(), getCode(), getWorld().isRemote);
}
```
The same command is still being used in 1.19, just its returning an EnderContainer rather then a FluidTank now.
