### ISSUE TITLE
Crashes on launch when using Terraqueous

### ISSUE THREAD

**Issue by BudderyShloofy** [ShetiPhian/Localizations-and-Issues#382]
So every mod from you works except for terraqueous, I wanted it so I could use the BYG mod. Not sure if its one of my other mods doing it or what. Ill attach the crash report and the mods that I am using.
[crash-2022-11-14_16.17.10-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/10007243/crash-2022-11-14_16.17.10-client.txt)
![Screenshot (71)](https://user-images.githubusercontent.com/63467139/201769016-fc9e0f07-c670-4685-8f32-d2dc94bb5f8c.png)

**Comment by ShetiPhian** [comment]
The Forge OBJ model renderer is crashing because the method its using is missing.

```
java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.block.model.BakedQuad.<init>(int[], int, net.minecraft.core.Direction, net.minecraft.client.renderer.texture.TextureAtlasSprite, boolean, boolean)'
	at net.minecraftforge.client.model.pipeline.QuadBakingVertexConsumer.m_5752_(QuadBakingVertexConsumer.java:131) ~[forge-1.19.2-43.1.43-universal.jar%23229!/:?] {re:classloading}
	at net.minecraftforge.client.model.obj.ObjModel.makeQuad(ObjModel.java:461) ~[forge-1.19.2-43.1.43-universal.jar%23229!/:?] {re:classloading}
```

In 1.19.1 the BakedQuad constructor only took `int[], int, Direction, TextureAtlasSprite, boolean` (quadData, tintIndex, direction, sprite, shade) 
In 1.19.2 Forge patched BakedQuad to accept another boolean at the end for hasAmbientOcclusion.

Either their patch isn't being applied, or something is replacing the class afterwards to make their own changes.

Try pulling OptiFine, it makes many changes to rendering and has had issues with breaking Forge.
(Also disable their Render Regions, I don't know what is was designed to do but it caused log spam when it runs into custom models like Multibeds and Platforms use)

**Comment by BudderyShloofy** [comment]
Getting rid of OptiFine fixed it. Do you know any good alternatives? (One that wont cause just as many issues preferably)

**Comment by ShetiPhian** [comment]
Mojang and Forge have both done a decent job at removing the need for performance mods.
I can't help with shaders as I don't use them so have never looked into them.

OptiFine is rather responsive though, If you report to them there is a crash with the latest Forge builds, it shouldn't be too long before a new build is released.

Just hover over this code block and press the copy button that appears, then paste it into your issue report.
````
```
java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.block.model.BakedQuad.<init>(int[], int, net.minecraft.core.Direction, net.minecraft.client.renderer.texture.TextureAtlasSprite, boolean, boolean)'
	at net.minecraftforge.client.model.pipeline.QuadBakingVertexConsumer.m_5752_(QuadBakingVertexConsumer.java:131) ~[forge-1.19.2-43.1.43-universal.jar%23229!/:?] {re:classloading}
	at net.minecraftforge.client.model.obj.ObjModel.makeQuad(ObjModel.java:461) ~[forge-1.19.2-43.1.43-universal.jar%23229!/:?] {re:classloading}
```
````

Here is a link to the Forge patch file that needs to be applied to BakedQuad
https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/patches/minecraft/net/minecraft/client/renderer/block/model/BakedQuad.java.patch

**Comment by BudderyShloofy** [comment]
Ah I will keep a look out for a patch on OptiFine then. Thank you for the help though!
