### ISSUE TITLE
Color bands of the Ender chests fade when biome blending is enabled.

### ISSUE THREAD

**Issue by spinodal23** [ShetiPhian/Localizations-and-Issues#385]
**Describe the bug**
Color bands of the Ender chests fade when biome blending (option of Sodium mod) is enabled.
As you can see in the images at the bottom, enabling the biome blending option fades the color bands of the ender chests.
As I added some biome addition mods into my server, I really want to turn on the biome blending option.

**Additional context**
Minecraft Version: 1.19.2
Forge Version: I'm using Fabric. Fabric API: 0.67.1 / Fabric Loader: 0.14.10
ShetiPhian Core Version: 1.3.3
My Mod(s) Name & Version: enderchests-fabric-1.19-1.1.0
Are other mods present? Yes
If yes:
- Does everything work without my mods? Yes
- Have you tested with only my mods? Yes

PasteBin or GitHub Gists links
latest.log = 
debug.log =
→ 4 screen capture images would be enough. Changing the biome blending option does not print any logs.

![2022-12-01_23 19 38](https://user-images.githubusercontent.com/96723542/205080893-d7a72844-516a-47d8-a575-f9a767341d1b.png)

![2022-12-01_23 20 15](https://user-images.githubusercontent.com/96723542/205080928-197f8db5-0615-4eb7-98b3-fdc9100eb491.png)

![2022-12-01_23 21 08](https://user-images.githubusercontent.com/96723542/205080969-87897ddc-4257-4497-8850-3c5c4498e39d.png)

![2022-12-01_23 21 27](https://user-images.githubusercontent.com/96723542/205080998-c1ac251e-9415-4740-995d-1a39fccd4b82.png)

**Comment by ShetiPhian** [comment]
Its a Sodium error, their current code blends all color providers.
They are aware and working on a fix.

**Comment by rjuven2401** [comment]
Oh yeah it is here: https://github.com/CaffeineMC/sodium-fabric/issues/895
Thank you, I'll then wait for the update of sodium.

**Comment by rjuven2401** [comment]
Being fixed: https://github.com/CaffeineMC/sodium-fabric/pull/1360

**Comment by ShetiPhian** [comment]
It will be nice to have this issue fixed.

Also since I'm currently porting Terraqueous I've made use of their blendable_blocks tag (added my leaves and vines)

**Comment by rjuven2401** [comment]
On version 1.19.2, this problem can be solved using [this](https://www.curseforge.com/minecraft/mc-mods/unofficial-sodium-biome-blending-fix/files/3948174).
On version 1.19.3, I think using latest version of sodium solves the problem, but did not tried yet.

**Comment by Mattabase** [comment]
![image](https://user-images.githubusercontent.com/2126947/217650292-9ddc3e94-6adf-47fa-bb0c-4550e90fcba2.png)

Still happens in 1.19.3
Sodium 0.4.9+build.23
Induim 1.0.14

**Comment by ShetiPhian** [comment]
You know, when the issue was first opened and I read September on Sodiums tracker I thought it was a new problem.
But now I see its over a year old and the pull request to fix it was more then half a year ago.

I should have known the same mod that doesn't care it breaks the Fabric Rendering API also wouldn't care its breaking other mods blending.


Kind of feel like Thanos "Fine, I'll do it myself"
Maybe I'll make a fix mod for 1.19.3 and mixin into their method to implement the pull request
Time stone sure would be nice right now, maybe then I could get through my ever growing to do list. lol

**Comment by ShetiPhian** [comment]
Give this a go:
https://www.mediafire.com/file/bzkmawzvp44ljnm/sodiumbiomeblendingpatch-fabric-1.19.3-1.0.jar/file

Not much to the mod.
Mixin into Sodium LinearColorBlender.getColors
Check if the passed block/fluid state is in the hardcoded defaults (from the Pull Request) or the c:blendable tag
If so let their code run, otherwise cancel and return the unblended color
