### ISSUE TITLE
You are failing to invalidate your capabilities on block entity removal.

### ISSUE THREAD

**Issue by KingLemming** [ShetiPhian/Localizations-and-Issues#404]
**Describe the bug**
As title. 

**Mod**
Ender Tanks

Version doesn't matter, core doesn't matter.

The recommended way of using capabilities to cache them locally in your tiles and invalidate them when the tile is removed. There are various interactions where other blocks have cached your neighbor cap (and have added a listener, waiting for invalidation), and the invalidation never comes, even after your tile is gone. This is a memory leak and also produces some very weird in-game interactions.

EDIT: I was overly annoyed in writing the initial comment as there is a standard for this sort of thing and it just irks me a lot to see it not used.

**Comment by ShetiPhian** [comment]
Guess I followed a bad example when I first implemented them; since worked I never thought anything of it, and continued implementing them the same way.

I believe my ender chests/tanks are the only ones not cached, but I know none are being manually invalidated.

This likely explains the strange behavior with RS I get the odd report of but haven't been able to reproduce.

I have some reading and corrections to do.
Thankyou for the heads-up
