### ISSUE TITLE
[1.19.2] Ender chests set to team can't be broken and Team Invite says an Unknown error has occurred 

### ISSUE THREAD

**Issue by MrPurple6411** [ShetiPhian/Localizations-and-Issues#406]
I placed an Ender chest and put an emerald on it but now when I try to break it I get "only a team member can perform that action". I can still access the chest, however.

This seems to be the same issue as [this one](https://github.com/ShetiPhian/Localizations-and-Issues/issues/125) but I am on ATM8 modpack on 1.19.2 and that issue says it is closed and resolved.

Also on another issue..... Trying to Invite anyone to my team says that an unexpected error has occured but the server admin says nothing is showing in the console logs

Minecraft Version: ATM8 modpack v1.0.14 on 1.19.2 minecraft on a server.
IGN: MrPurple6411
Server: atf8.minecraft.best
Forge Version: 43.2.6
ShetiPhian Core Version: shetiphiancore-forge-1.19.0-3.11.3.01

**Comment by afekw** [comment]
I also have the same problem on a forge server

**Comment by ShetiPhian** [comment]
Sorry for the delay.

Teams was plagued with several little bugs, but as for the two you pointed out
- Not being able to break chests or tanks was due to the client missing what team the player was on
- Invite was broken because I changed the compare from == to .equals, and didn't notice the variables were backwards, resulting in me basically running "if null.equals(team)"

After that there was a few name sync issues, ways for the leader to leave without transferring, players could be listed several times causing issues with leaving/kicking, unable to transfer leader to a manager, and the logging from admin commands was useless due to lack of info.

Latest builds have the fixes.
