### ISSUE TITLE
[Suggestion] Dyenamics compat

### ISSUE THREAD

**Issue by HanatakeYurii** [ShetiPhian/Localizations-and-Issues#411]
Multibeds is awesome. And it could be even more awesome if it supported the extra dyes added by Dyenamics (made by TeamCoFh, authors of Themal Expansion & co.).

So I would like you to consider that, or if you feel it's more appropriate ask on their side (if the feature is exposed enough).

Anyway, I don't to pressure anyone, the choice is up to you, the mod stay awesome in any case. Thanks for your work

**Comment by ShetiPhian** [comment]
Blanket support has a few issues
-  a unique texture per dye due to them not looking good when tinted. (126 new textures needed)
-  an enum which is tied to the original dyes. (could be reworked)
- I don't think json recipes can be dynamically loaded. So it will either throw errors or Dyenamics becomes a requirement)


Pillows and Sheets already support 4096 colors through crafting/dyeing with multiple dyes (first sets color, rest mix in order)
I could probably add support for the extra dyes to jump to that color. (And due to this being a recipe in my core it would also enable support on dyable blocks in Terraqueous.)

**Comment by HanatakeYurii** [comment]
I understand your issue. Pillows and Sheets would already be wonderful.

Tell me if I can ask them anything, they already have a compatibility dedicated mod for Dyenamics ([Dyenamics and Friends](https://github.com/JDKDigital/dyenamicsandfriends))

**Comment by ShetiPhian** [comment]
At the moment there is nothing to ask.
Without the blanket code rework any compatibility would need to be rather hacky.
As for the pillows and sheets, its just changing the recipe to check for the added dyes and apply the wanted color. That can be directly baked into my core.

I'll look into it after I finish up the 1.19.4 and 1.20.1 ports
(currently trying to figure out DataFixers, basically no examples and both Forge and Fabric have removed the class the few examples used to register them)

**Comment by HanatakeYurii** [comment]
Thank you and good luck with DataFixers!

**Comment by ShetiPhian** [comment]
I did look into this but forgot to update here.
While I could add references to the value map, it wouldn't end up doing anything as most code that uses it is tied to the default dye enum.

I've noted it as a possible future rework given the time to do so.
