### ISSUE TITLE
Can't Break Tank From Another Player Even if it is Disabled in the Config

### ISSUE THREAD

**Issue by Aiidoneus** [ShetiPhian/Localizations-and-Issues#412]
**Describe the bug**
Hello, from what I can tell, I disabled all tank owner and team locks on the tanks all together. My goal is to allow my server to move another person's tank but I just can't get it to work at all. I set the following in the endertanks.toml in attempts to get this done. 
`personal_edit_lock = false`
`team_edit_lock = false`
`personal_link_lock = false`
`team_link_lock = false`
`personal_use_lock = false`
`team_use_lock = false`

**Additional context**
Minecraft Version: 1.19.2
Forge Version: 1.19.2-43.2.14
ShetiPhian Core Version: 1.19.0-3.11.3.04
My Mod(s) Name & Version: endertanks-forge-1.19.0-1.12.1.04
Are other mods present?
If yes:
- Does everything work without my mods? N/a
- Have you tested with only my mods? Yes

PasteBin or GitHub Gists links
latest.log = N/a
debug.log = N/a

**Comment by ShetiPhian** [comment]
I was just testing this now (on 1.20 but this part is the same) and its working.
The edit locks have to be set to false in both Client and Server configs though.

Harvesting is done by the Client, then sent to the Server, which decides if the block was actually broken and generates drops.
Client needs to know to make the attempt, and the Server needs to allow it.

The Client doesn't skip this check because if the server side blocks it you end up with a block that temporarily vanishes that the player can fall through thus getting stuck in or suffocating. (also get particles on each break, and a stuck breaking overlay, but those are just visual)

This is a case where server synced common configs would be helpful
