### ISSUE TITLE
Crash after some time loading into a world

### ISSUE THREAD

**Issue by nico42069** [ShetiPhian/Localizations-and-Issues#414]
**Describe the bug**
The game crashes little after i load in a world

**Additional context**
Minecraft Version: 1.12.2
Forge Version: 
ShetiPhian Core Version: 
My Mod(s) Name & Version: 
Are other mods present?
If yes:
- Does everything work without my mods?yes
- Have you tested with only my mods?no i want to make a modpack

PasteBin or GitHub Gists links
latest.log = 
debug.log =
[crash-2023-08-30_13.11.39-server.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/12475022/crash-2023-08-30_13.11.39-server.txt)

**Comment by ShetiPhian** [comment]
Its due to some other mod incorrectly adding a null item to the forge ore dictionary. Since it shouldn't exist the entries are not checked before processing.

If you don't care about the doodads they can be disabled via configs (or at least stopped from generating)
The other option is to change the whitelist so it doesn't use ore dictionary entries, and provide a list of items instead.
