### ISSUE TITLE
I load into the game completely fine but when I go to play chunks of the world don’t load in and my render distance is at max

### ISSUE THREAD

**Issue by xXshadowWolf** [ShetiPhian/Localizations-and-Issues#415]
**Describe the bug**
I load into the game completely fine but when I go to play chunks of the world don’t load in and my render distance is at max

**Additional context**
Minecraft Version: 1.20.1
Forge Version: 47.1.3
ShetiPhian Core Version: 
My Mod(s) Name & Version: EnderTanks -1.20.1-1.0
Are other mods present?
If yes:
- Does everything work without my mods?
- Have you tested with only my mods?

PasteBin or GitHub Gists links
latest.log = [latest.log](https://github.com/ShetiPhian/Localizations-and-Issues/files/12647516/latest.log)
debug.log =[debug.log](https://github.com/ShetiPhian/Localizations-and-Issues/files/12647515/debug.log)

**Comment by ShetiPhian** [comment]
Neither EnderTanks or ShetiPhianCore have worldgen or do anything on chunk load.
That pack is throwing a lot of errors a few concerning ones are mixins not loading correctly, as this will result in unexpected behavior. (if your not running in a mod development environment, something is very wrong as I can't see so many mod jars being corrupt)
JEI also has thrown an error about game events failing (this shouldn't happen)
There also appears to be many null's registered and broken recipes.

With so much broken its hard to tell the root cause.

Start with a clean instance with only EnderTanks and ShetiPhianCore.
Then look at the latest.log and make sure this line does not appear (it will be near the top):
`[main/WARN] [mixin/]: Reference map 'mixins.endertanks.refmap.json' for mixins.endertanks.json could not be read.`

If its not there add a few mods at a time until the pack breaks, then look over the ones just added.
