### ISSUE TITLE
[1.20.1] [FORGE] invisible beds, MultiBeds incompatible with CHISEL REBORN mod

### ISSUE THREAD

**Issue by A00826925** [ShetiPhian/Localizations-and-Issues#416]
**Describe the bug**
Beds and ladders are invisible with my modpack, im continuing to make tests to determine what it its, but i wanted to post this in case you already know incompatibilities and i can save some time in testing.

Here is my latest log: https://mclo.gs/5dIvqUW

Im running sinytra connector and forgifiedAPI to run fabric mods on Forge. All other mods that add 3D models load fine. 

**Additional context**
Minecraft Version: 1.20.1
Forge Version: 47.1.3
ShetiPhian Core Version: 1.20.1-1.0
My Mod(s) Name & Version: Multibed 1.20.1-1.0
Are other mods present? Yes
If yes:
- Does everything work without my mods?
-Yes
- Have you tested with only my mods?
- Yes, they work.

PasteBin or GitHub Gists links
latest.log = https://mclo.gs/5dIvqUW
debug.log = https://mclo.gs/dQtSi8f

**Comment by A00826925** [comment]
loading with the following mods started breaking the textures on world load, making all ladders look the same until a new ladder was placed, and every singled placed ladder refreshed, but i could still see the models: 
![image](https://github.com/ShetiPhian/Localizations-and-Issues/assets/73501467/49119779-b031-40a4-8af5-9cf9edfc6b11)

**Comment by ShetiPhian** [comment]
Beds & Ladders (MultiBeds), All Chests (MultiStorage), All Platforms (Platforms), Pergolas (Terraqueous)
All of those use custom models, the Fabric builds require the Fabric Rendering API, and the Forge builds require the methods Forge adds to the model classes.

Anything that breaks the custom model support (eg. Sodium, Optifine) will result in them being invisible. (normally fixed by adding Indium, OptiForge)


betterx.worlds.together is throwing an error on the render thread about Forge mods lacking a fabric.mod.json (Forge mods won't have these)
Though that's unlikely to be the issue.


Invisible blocks is likely due to something reverting Forges changes and is calling the original BakedModel.getQuads method instead.

As for the new issue, order of operations has been messed up, and the block is being rendered before the model data in the tile entity is loaded/fetched. And because Minecraft caches chunk render data until an block update, the models use the default/fallback texture until the model gets reprocessed. (Most likely is the first fetch Forge does isn't being done anymore, so it only happens on update)

**Comment by ShetiPhian** [comment]
My guess is the changes to make Fabric mods work are currently breaking Forges baked model and model data.

You could give the Fabric builds a try, its possible enough of the API is ported form them to work.

**Comment by A00826925** [comment]
had to replace forge cloth to fabrics cloth for the fabric build to run on forge, but unfortunately i still have the same issue, plus i dont think its the fabric port to forge since tests with that installed managed to work just fine, so im still looking for the incompatibility.

**Comment by A00826925** [comment]
The problem was the mod "Chisel Reborn" which, for some reason, generates jars for continuity, chisel and templates. kinda weird how it does that.

**Comment by ShetiPhian** [comment]
The extra jars might be jar-in-jar and just being unpacked.
I do wonder what they are doing to the renderer though.
Maybe I can find out as I just added a similar logged error as I have for Fabric when its API is broken (didn't need it in Forge as only Optifine broke it but caused a crash)

**Comment by ShetiPhian** [comment]
So I started with `Forge 47.1.3`, MultiBeds, `Connector-1.0.0-beta.15+1.20.1-full`, `fabric-api-0.88.1+1.9.14+1.20.1`
Verified things worked then added `chisel-1.6+1.20.1+templates2-inside` and `continuity-3.0.0-beta.3+1.20.1` expecting to have invisible beds and a new error in the log, but things still worked.

I thought maybe a conflict with Continuity, not working correctly on Forge as it was never intended to be there. (and because it compares itself to Optifine)

Unless one of those has updated since your pack, there is another mod at play.

**Comment by A00826925** [comment]
I think it might be sinytra connector and forgified api, although i have not tested yet. Since continuity is a fabric mod (i think right?), sinytra connector might be loading it (since its purpose is to load fabric mods). Chisel reborn might be using that continuity jar in another way, but since sinytra is there, it loads. Again, No tests yet.

**Comment by A00826925** [comment]
Oh my bad, i misread, you already tried that. But still, its not an issue with your mod, so all should be fine!

**Comment by A00826925** [comment]
to end ill share my modlist, my BEDS stopped working with these mods + Chisel Reborn (not listed here) 
![image](https://github.com/ShetiPhian/Localizations-and-Issues/assets/73501467/49fccb3a-928f-4249-99d9-0e55a9717bf2)
