### ISSUE TITLE
[1.20.1] [FORGE] [low priority] Unable to climb up trapdoors from a Bunk Ladder

### ISSUE THREAD

**Issue by A00826925** [ShetiPhian/Localizations-and-Issues#417]
Latest Version of Both Core and Beds, cant climb up from a bunk ladder, into a trapdoor, into another bunk ladder, like so: 
![image](https://github.com/ShetiPhian/Localizations-and-Issues/assets/73501467/0f012a37-7b6a-4bb2-a621-a71098d709f0)

Normal ladder on bottom allows you to climb, meaning the issue is with the top of the bottom ladder maybe having too short
of a hit box.

**Comment by ShetiPhian** [comment]
Its because my ladders have the opposite facing from the Minecraft ladders, resulting in the trapdoors ignoring them.

And that is due to a difference in modeling. All of the modeling programs I've used have a facing north orientation, so everything is modeled that way. Minecraft however has models with different orientations, and the Ladders are one of them.

Rotating the models and hitboxes would solve it on all versions, but players would have to manually correct the now backwards blocks.
Forge 1.20 has a method I could override to fix it, don't know if it exists back in 1.16 though, and Fabric would require a Mixin to special case my ladders.

**Comment by ShetiPhian** [comment]
Fixed in latest builds
