### ISSUE TITLE
new Crash to Desktop 1.18.2

### ISSUE THREAD

**Issue by I2pRandom** [ShetiPhian/Localizations-and-Issues#426]
**Describe the bug**
Game crashes to desktop on startup

**Additional context**
Minecraft Version: 1.18.2
Forge Version: 40.2.14
ShetiPhian Core Version: 3.10.17
My Mod(s) Name & Version: 
Are other mods present?
If yes:
- Does everything work without my mods?
- Yes
- Have you tested with only my mods?
- No, i can't remember which mods require it and don't.

PasteBin or GitHub Gists links
latest.log = https://gist.github.com/I2pRandom/9ff0e8c83ea2281d75081123835ac9c9
debug.log = https://gist.github.com/I2pRandom/d27ecff8b468d30235ec69f3a3bf2d5a

**Comment by ShetiPhian** [comment]
I'm not seeing a clear indication of what is causing the crash.
I see many mixin issues, but none of them are conflicts with my own.

Finding the conflict would require splitting the pack in half and testing, if it doesn't work split again and if it does add a few more back, then test again. Eventually you'll end up with a few mods that just don't play nice with each other.
Alternatively since the pack works without my mods you can save the hassle and just pull them out (you can try with just the core, and if that works adding the others back one at a time, because it may not be an conflict with the core)

**Comment by ShetiPhian** [comment]
This might be related to https://github.com/ShetiPhian/Localizations-and-Issues/issues/434 but the other mod is crashing instead of mine.
