### ISSUE TITLE
Craft furnace is not a furnace for mods and data packs that check for furnace code.(1.19.2)

### ISSUE THREAD

**Issue by Sheep-Hugger** [ShetiPhian/Localizations-and-Issues#431]
Its missing the stuff to make it count as furnace for items or global effects that alter furnaces or accelerate them.

**Comment by ShetiPhian** [comment]
Should work by triggering addition block ticks, maybe something furnace specific is looked for.
What item isn't working? I'll look into how its working and see if I can adapt.

**Comment by ShetiPhian** [comment]
I thought about maybe extending the furnace tile entity but that's not happening
I'd have to duplicate a lot of code, redirect several methods, and use reflection to overwrite some final variables that it creates because the values would be invalid for my blocks.

I'm already adding the block to the furnace tags, so anything that speeds up furnaces can be using that tag to know what blocks to alter and send additional ticks. (or with an event/hook they can block ticks to slow it down)

**Comment by Sheep-Hugger** [comment]
Sorry haven't played Minecraft in a while, thanks for fixing it ill probably get to test it next time i get into Minecraft, i tend to include you mod for years now when i play.
