### ISSUE TITLE
1.20.1 | EnderChests | Dupont, with the help of the ender chest and tank.

### ISSUE THREAD

**Issue by DesiRe234** [ShetiPhian/Localizations-and-Issues#433]
**Describe the bug**
Dupont, with the help of the ender chest and tank. I found two duplicates associated with the loss of diamonds. 
1. At some point, as in the video, a diamond falls out of the chest, but the chest still remains personal, not publicly available. In about half an hour of such actions, + 3 diamonds fell out.
Video replay: https://youtu.be/9e58boEJzPw и https://youtu.be/BmtvzpoofgA
2. It was also possible to understand that diamonds get stuck if you break a chest or tank in flight with a shift.
Video replay: https://www.youtube.com/watch?v=puAFaZUL-lw и https://www.youtube.com/watch?v=_MxSn-nbiHE

**Meta**
Item.of('enderchests:ender_chest', '{code:""000"",owner:""all""}')
'minecraft:diamond' - diamond
'enderchests:ender_chest' - chest
'endertanks:ender_tank' - tank

**Additional context**
Minecraft Version: 1.20.1
Forge Version: 47.2.1
ShetiPhian Core Version: 1.20.1-1.2
My Mod(s) Name & Version: EnderChests 1.20.1-1.2
Are other mods present?
If yes:
I haven't tried it without other mods, but I'm sure they're not the problem.

**Comment by ShetiPhian** [comment]
I don't know if its the tool, server lag or some odd conflict, but I can't reproduce the dupe with just the tanks/chests.

I've placed eight and broke them over and over again. Every time if I wasn't sneaking the personal version dropped, and if I was sneaking the public one dropped with a diamond.

To test if the issue was due to the speed that tool broke them I made them instant break. While all eight broke in only two clicks now, every time the correct drops happened.

I'm not even sure how its happening, the getDrops method reads the loot table then checks the tile entity for additional drops. The players sneak flag would need to be false for the loot table and true for the additional drops, that is within a millisecond. (also I don't think that is threaded so it can't change while within the method)
