### ISSUE TITLE
Waterlogged Stairs Impossible with Ender Bucket

### ISSUE THREAD

**Issue by DeeJayhX** [ShetiPhian/Localizations-and-Issues#440]
**Describe the bug**
You are unable to waterlog stairs with an ender bucket like you can with a regular bucket. The water will appear on top of the stairs instead of inside of the step. This has consistently been an issue for years on ATM modpacks. I assume this is something that was just never considered/implemented since it became a thing in vanilla minecraft. It would be *very* useful for large projects involving waterlogged stairs and useful far beyond just the purview of modpacks, even if just Ender Tanks was being used.

**Additional context**
Minecraft Version:           1.18.1   | 1.19.2   | 1.20.1
Forge Version:                 40.1.80 | 43.2.14 | 47.2.20
ShetiPhian Core Version: 3.10.10 | 3.11.10 | 1.2
My Mod(s) Name & Version: ATM7 | ATM8 | ATM9
Are other mods present? Yea...

**Comment by ShetiPhian** [comment]
Fixed in latest builds uploaded to Curse and Modrinth.

Note on Curse: I have no idea when the download will be publicly available.
Something has changed between November and now, as every one of my recent uploads has be sent for manual review and that takes several hours/days; before the automated system scanned them and posted within minutes.
