### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by al-wei** [ShetiPhian/Localizations-and-Issues#446]
**Describe the bug**

Game crash
---
**Additional context**
- Minecraft Version: 1.12.2
- ModLoader & Version: Forge 14.23.5.2860
- Side: (SinglePlayer)
- ShetiPhian Core Version: shetiphiancore-1.12.0-3.5.9
- My Mod(s) Name & Version: terraqueous-1.12.2-1.4.17b

Are other mods present?
- Does everything work without my mods?
- Have you tested with only my mods?

PasteBin or GitHub Gists links
- latest.log = 
- https://gist.github.com/al-wei/764572690ce0365460a27852a5768838
- https://gist.github.com/al-wei/dc3e1c1a5b2db85fb51bfec880205126
- https://gist.github.com/al-wei/f218cdcf6721a80fad0afc4da10d3ee5

**Comment by ShetiPhian** [comment]
1.12 is not supported anymore

I'm aware of this bug, but the first time it was reported was after I stopped supporting 1.12 and the development environment died.
Its caused by a null stack being in the ore dictionary, as one should never exist there I never wrote an error handler for it.
I do know a workaround though; In the config file, remove all dictionary entries from doodad white/black lists. Drops will need to be defined per item though.
