### ISSUE TITLE
Occasional IndexOutOfBoundsException during normal gameplay

### ISSUE THREAD

**Issue by SparkyTD** [ShetiPhian/Localizations-and-Issues#451]
**Describe the bug**

I found an exception seemingly caused by the mod Terraqueous, that happens very rarely when opening a chest, or other inventory block. I have no idea if it's related to the items in the inventory at all, because it happens so rarely, and also after restarting the game and opening the same chest again, the crash no longer happens.

---
**Additional context**
- Minecraft Version: 1.20.1
- ModLoader & Version: Forge 47.3.5
- Side: SinglePlayer
- ShetiPhian Core Version: 1.20.1-1.3
- My Mod(s) Name & Version: Terraqueous 1.20.1-1.4

Are other mods present?
- Yes, full mod list [here](https://0x0.st/XWPK.txt), but testing it with/without your mods would be impossible because this crash happens approximately once every ~5-10 hours of gameplay, and is not consistent or repeatable.

In the specific crash attached below, it happened after opening an OpenComputers II Reimagined robot's GUI. But the same exact exception has happened before while opening a vanilla oak chest.

PasteBin or GitHub Gists links
- latest.log = https://0x0.st/XWPZ.log
- crash-2024-08-10_00.50.36-client.txt = https://0x0.st/XWPP.txt

**Comment by ShetiPhian** [comment]
_(not sure what's up with the linked/mentioned issue report, this bug has nothing to do with it)_

I understand why my chest renderer is crashing, just not sure the underlining trigger, but that doesn't mater anyway.
I'm using the tileentity blockstate to obtain the id, then trim it to length - 6 to remove "_chest"
for whatever reason the blockstate is air, resulting in a trim length of -3, thus a crash.

Since it happens so randomly in large packs, I'm guessing some kind of race condition where the renderer starts before all data is setup. Adding a check to make sure the id ends with chest before trimming it will fix the crash.

**Comment by ShetiPhian** [comment]
New builds are up.

The infrequent nature of this meant I couldn't test, but I'm quite sure what the issue was.
