### ISSUE TITLE
small stones and fallen branches spawn with "Darklands Grass"

### ISSUE THREAD

**Issue by LemADEC** [ShetiPhian/Localizations-and-Issues#51]
As of terraqueous-1.10.0-1.2.18, with AbyssalCraft-1.10.2-1.9.3.10, small stones and fallen branches are spawning on top of Dark oak leaves and branches, instead of below it, on top of "Darklands Grass"

**Comment by ShetiPhian** [comment]
The changes in 1.2.18 has no effect on where my items are placed. It corrected the position given to an event which could trigger other mods to generate additional chunks.

I'm using a slightly modified version of World.getTopSolidOrLiquidBlock, modified because unlike the name implies it doesn't return liquid blocks. (also added a double tall plat check)

Dark Oak Leaves must be returning false to both Block.isLeaves and Block.isFoliage, as returning true to either would make it an invalid block.

**Comment by LemADEC** [comment]
That's our first time testing terraqueous with AbyssalCraft, so I guess the issue is there for some time.

Looks like the AbyssalCraft logs and leaves are based on vanilla BlockLog and BlockLeaves: 
https://github.com/Shinoow/AbyssalCraft/blob/1.10.2/src/main/java/com/shinoow/abyssalcraft/init/BlockHandler.java#L59
https://github.com/Shinoow/AbyssalCraft/blob/1.10.2/src/main/java/com/shinoow/abyssalcraft/common/blocks/BlockACLog.java#L24
https://github.com/Shinoow/AbyssalCraft/blob/1.10.2/src/main/java/com/shinoow/abyssalcraft/common/blocks/BlockACLeaves.java#L38

@Shinoow any thought on that issue?

**Comment by Shinoow** [comment]
Opening a test world, it seems like the small stones and fallen branches are ignoring the leaves, but consider the logs valid (thereby replacing the leaf block above).

**Comment by ShetiPhian** [comment]
As it turns out getTopSolidOrLiquidBlock doesn't make sure the position is empty before returning it.
I've added an additional check to do just that.

Here is the latest 1.11 build:

http://www.mediafire.com/file/5t2cjz3gih2mgb0/shetiphiancore-1.11.0-3.4.3-rb1.jar
http://www.mediafire.com/file/3egn62cg6j5y9yl/terraqueous-1.11.0-1.3.7-rb3.jar

**Comment by Shinoow** [comment]
Yeah, that fixed it.

**Comment by LemADEC** [comment]
Excellent!
Any idea when we can get a public release for this fix?

**Comment by ShetiPhian** [comment]
Now :)
..... well when it leaves the "Under Review" status and Curse makes it available.
