### ISSUE TITLE
[1.11.2] Config option for Trickster bloom applying random status effects

### ISSUE THREAD

**Issue by MrNinja93** [ShetiPhian/Localizations-and-Issues#52]
Could there be some kind of config option to enable/disable the trickster bloom applying random status effects? Or at the very least a config for each flower so only it can be disabled similar to the tree generation configs currently.

As an aside/related note the status effects last indefinitely once obtained in most cases until a player dies or relogs, I assume it's intended but mentioning just in case it isn't. Night vision flickering constantly is the main concern with strobe lighting type effect potentially having adverse reactions on people.

**Comment by ShetiPhian** [comment]
Not intended, it should be working like this:
- Player steps on a flower, if they are not already in the list they are added along with a random time.
- When the random time has elapsed, player is removed from the list.
- A random effect is picked from another list and applied.
- Minecraft handles the effect like any other and it times out like normal

I'll look into the bug, and add a config for setting the effects.

**Comment by ShetiPhian** [comment]
I wasn't getting the unending status effects, but it was likely due to a server/client desync of some sort.
The tracker is now based on uuid and handled server side so it shouldn't be able to happen any more.

There is also a new config option for configuring what effects can be applied.

New builds are up on Curse

**Comment by WesCook** [comment]
Not sure if this is related, but I've seen an issue where I get the Quark Curse effect constantly set to 0:00.  I've been trying to find the cause for ages.

It wasn't in the effects list, but does sound like the issue you reported.

**Comment by ShetiPhian** [comment]
That, and perhaps the original report, is not the Trickster bloom.

Mod added status effects where not in the hard coded list, and now only items from the config list are used. 
I've also moved handling to the server side to make sure the possibility of a desync can not happen.

As before; after a status effect is applied it is completely handled by vanilla Minecraft, it will use the same countdown and removal systems as potions.

**Comment by WesCook** [comment]
Yeah, I'm sure you're right.  I thought it was odd that a Quark effect
would be included but it was my best guess.

I kept seeing random effects (especially Luck and Unlucky) from this
flower, so i thought it may be the same mechanism at work.

The hunt continues for the phantom 0:00 Curse effect then.

On Mar 27, 2017 03:27, "ShetiPhian" <notifications@github.com> wrote:

That, and perhaps the original report, is not the Trickster bloom.

Mod added status effects where not in the hard coded list, and now only
items from the config list are used.
I've also moved handling to the server side to make sure the possibility of
a desync can not happen.

As before; after a status effect is applied it is completely handled by
vanilla Minecraft, it will use the same countdown and removal systems as
potions.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ShetiPhian/Localizations-and-Issues/issues/52#issuecomment-289414545>,
or mute the thread

**Comment by MrNinja93** [comment]
The only effects I ever experienced were the vanilla ones now listed in the config, no mod added ones. 

Ever since avoiding the flower it never happened again so it was definitely the flower adding. The unending effect though could have been a mod interaction, sadly those can be a nightmare to track down reliably.
