### ISSUE TITLE
EnderTable acting funny and not giving what it says.

### ISSUE THREAD

**Issue by oneandonlyflexo** [ShetiPhian/Localizations-and-Issues#59]
I'm experiencing some strange behavior with the Ender Table/Ender Monocle interaction.  I see some good enchants that I would love to have, and when I select them, I get a completely different set of enchants on my items.  Also, the enchants seem to vary a lot in level even when I select the level 30 (e.g. selected a level 30 enchant to some leggings and got protection 1).

**Comment by ShetiPhian** [comment]
I removed my code that sent that enchant data to the client due to 1.11 already doing so. (or at least appeared to be doing so)
I'll have to put that back in.

**Comment by ShetiPhian** [comment]
So it turns out I didn't remove that code after all, the default code must have been lacking in some way.

I did run a few quick tests in single player and everything enchanted correctly, I didn't get the chance to see if the display is wrong when connected to a server though.

Do you have other mods in that add/change enchants?
Was it a mod added item/enchant that failed to display/apply correctly?

**Comment by oneandonlyflexo** [comment]
I'm playing on 0.5 version of Raxpack2.  It does include the Felling mod which adds a tree felling axe enchant to the pack.  Which is what i got when enchanting my axe.  However, when enchanting my armor and picks, I saw and received just standard vanilla enchants.

Perhaps the way that enchant is being added to the pool is causing the issue?  When I get home I'll try just adding those two mods alone and see if it happens.

**Comment by ShetiPhian** [comment]
I believe I've got it.

While testing on a server I had a good run of correct enchants, then every last one was wrong. 
Using breakpoints I notice the servers generation key was different then the clients, but that seemed odd as the server was sending it to the client.

Minecraft's SPacketWindowProperty class was the root cause of the issue;
The send and receive helper methods and the packet itself used an integer, but the packet only sent a short, so the upper 16bits where cut from the generation key the client received.
This caused any number bellow 0 and above 32,767 to be wrong on the client. (An integers range is -2,147,483,648 to 2,147,483,647 so there is a higher chance for the wrong number to be received then a correct one.)

To work within the packets limit I'm not using the players generation key directly anymore, rather I'm using it to generate a new one that is within the range of a short (-32,768 to 32,767). This one is synced to the client and used to generate the enchants.

**Comment by ShetiPhian** [comment]
Here is the test build if you want to try it out.

http://www.mediafire.com/file/mgi9kmjies3quga/terraqueous-1.10.0-1.2.22-rb1.jar
http://www.mediafire.com/file/w4a4reckq8z9cac/terraqueous-1.11.0-1.3.10-rb1.jar

**Comment by ShetiPhian** [comment]
Sorry for the delay,
New builds are up on Curse now.
