### ISSUE TITLE
EnderTank-Network lose connection

### ISSUE THREAD

**Issue by cyberpunkbln** [ShetiPhian/Localizations-and-Issues#6]
Hi,

at some times endertank-network loose connection. I dont can redproduce this. When i load a game when minecraft is fresh loaded, or when i disconnect and the reload a world.

Mostly the Endertanks connect to a network that deliver Syngas????

When i disconnect and delete the enderstorage-dir in saves/world then the networks will be reseted and my chunkloader in the nether make the correct delivery of lava:).

greets

Edit: I know this will be happend when i load a world, quit the world and load another or this world again without quitting minecraft.

**Comment by ShetiPhian** [comment]
It sounds like the network data isn't being cleared between worlds, so the previous worlds data is still present and get used.

I'll have to see whats going on as the world load event is clearing the data before loading the new files, so the old data shouldn't be crossing over between worlds.

**Comment by ShetiPhian** [comment]
Okay, I've spent some time on this and can only see one reason why it would happen; if the Overworld (Dimension:0) is not loaded or is unloaded.

I was using its load and save events to clear+load and save the tank data. Minecraft forces it to always be loaded, but it is possible with mods / sponge to override that behavior.

I now load when the server starts, unload when the server stops, and save when any world saves if anything has changed in the tank network since the last save.

**Comment by cyberpunkbln** [comment]
Hello,
thx for the build and the work. At the moment minecraft is loading and i will heavily test this build and write if my problems are solved.
thx

**Comment by cyberpunkbln** [comment]
So your Test-Build has resolved my problems, at no time the Network will loose. Thx.

**Comment by ShetiPhian** [comment]
Thank you for letting me know.
I've uploaded a new version to Curse.
The only difference between the one you have now and the new one on Curse is an adjusted EnderBucket texture.
