### ISSUE TITLE
Crash Report - Crashes eating ANY food from this mod....

### ISSUE THREAD

**Issue by trajik007** [ShetiPhian/Localizations-and-Issues#67]
[crash-2017-04-24_09.26.41-server.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/952493/crash-2017-04-24_09.26.41-server.txt)

Edit: I should have added that the mod affected is ONLY Terraqueous, and as far as I can tell it's ONLY happening when I try to eat foods from the mod. All other actions work fine (again, as far as I can tell from playing).

**Comment by ShetiPhian** [comment]
I just had another report this same issue.
-> Your version of Terraqueous is out of date, the conflict with the AppleCore ASM code has been fixed.

Same oddity too.
Your running the newest ShetiPhianCore (3.4.4 released Apr 8, 2017) but several versions behind on Terraqueous (1.3.6 released Jan 29, 2017)

The current build is 1.3.10 (released Apr 17, 2017), but the bug was fixed back in version 1.3.7 (released Mar 9, 2017)

If this it a pre-made mod pack please inform the pack maker they need to update Terraqueous.
