### ISSUE TITLE
Duplicating blocks

### ISSUE THREAD

**Issue by NoVac101** [ShetiPhian/Localizations-and-Issues#74]
https://youtu.be/aXdki6c5Vdk
Here's the example I've found.
Mod pack: All the Mods 2 1.11.2

**Comment by ShetiPhian** [comment]
Summery:
- Block implements IGrowable
- IGrowable has shortcomings
- due to shortcomings the other mod makes assumptions
- assumptions cause the bug you see. (and a different one with my trees leaves)

Reap was the only one with this conflict, and was solved using its blacklist. ATM2 doesn't seem to have Reap so it looks like I'm going to need to replace IGrowable.

**Comment by ShetiPhian** [comment]
In the newest build I no longer use IGrowable
