### ISSUE TITLE
Inventory Tweaks doesn't play well with stacked Stone Storage

### ISSUE THREAD

**Issue by Revvilo** [ShetiPhian/Localizations-and-Issues#76]
When a stacked Stone Storage inventory has items that are outside of the current GUI and require scrolling down to view, sorting the inventory just mixes the items around.
And if items that are off screen have a gap between them and other items, they will pop onto your cursor, or pop into your inventory if there is more than one.
<img alt="Gif of inventory glitching" src="https://cloud.githubusercontent.com/assets/13816212/26479295/30f2514e-4226-11e7-90eb-57dfdc1607cb.gif" width=350>
I realise this is cross mod support and might not be very easy to make stable, but I thought I'd lodge this here either way :3

**Comment by ShetiPhian** [comment]
I'll need to look over Inventory Tweaks's code and see how it does its sorting.
If Inventory Tweaks's is simulating clicks client side my only option may be disabling it from sorting those chests.


Scrolling makes visual changes and adjusts slot clicks.
All back end data structure is unaltered (inventory positions never change, and slot id's never change)

When you scroll, the location the slots are rendered at move into their new position. Slots that no longer need to be rendered are placed at 0,0 and have their rendering disabled. The new row of slots are moved from 0,0 into their place and are rendered.
Hidden slots are moved to 0,0 because they blocked clicks for the viable ones with lower id's.
Click processing is disabled for hidden slots, otherwise clicking at 0,0 interacts with them.

**Comment by ShetiPhian** [comment]
I took a look into this,
Inventory Tweaks does simulate the player clicking, and my locking of the hidden slot conflicted.

Rather then disable the support, my hidden slots where reworked a bit so the lockout wasn't needed
Not sure if this fix caused the interaction with EnderLinkChests to bug out or if the buttons on it never worked correctly in the first place, but has been fixed.

**Comment by ShetiPhian** [comment]
The newest build is now available on Curse

**Comment by Revvilo** [comment]
Absolutely brilliant. works perfectly now!
Appreciate all you've done very much :D
