### ISSUE TITLE
Client Crash IllegalArgumentException Enderlink bag

### ISSUE THREAD

**Issue by Dryxen** [ShetiPhian/Localizations-and-Issues#80]
Client crashes when Opening the bag Caverns mod water Dimension. 
heres the crash log.
https://hastebin.com/axonixaboj.pas

**Comment by ShetiPhian** [comment]
Odd owner name shouldn't be empty at that point as another method is called first that sets it to the owner id if the name is blank.

I also don't seem to be able to reproduce the issue.
Optional: try opening the bag again, if you crash send me your playerdata file

This build has an additional check where you crashed last time that should stop it.
http://www.mediafire.com/file/6462le9r16xbo65/multistorage-1.11.0-1.3.8-RB1.jar

**Comment by Dryxen** [comment]
havent checked the revision yet but logged into the server and reproduced the error, i wasnt sure which player data you needed so i grabed them from the world and the enderchests folders. as far as ive noticed this is only happening in that one dim havent had any problems in the overworld ect.

github didnt wanna support the zip =/ heres the first upload site i stumbled accross xD.

http://s000.tinyupload.com/?file_id=06118482013392133536

**Comment by ShetiPhian** [comment]
I'm not seeing the cause of this bug. Its acting as if the stack nbt data is bad, but looking at the playerdata file everything is fine.
Another thing bothering me is the code should be functioning the same regardless of the dimension.

**Comment by Dryxen** [comment]
confirm it still happening after revision seems its not only for that specific dim as it happened in the overworld as well i reset the link on the bag and it works 2 or 3 times and started crashing the client again.
heres the log. 
https://hastebin.com/atogurexek.pas
if theres any specific info i can help you out with lemme know.

**Comment by ShetiPhian** [comment]
The stack is fine in the player data, yet broken for this function. Something is deleting the item stack nbt data client side.

I can add a check for this and disable the bag, relogging would restore it, but that is just a band-aid, a real fix needs to be found.

This should throw an on screen error instead of crashing.
http://www.mediafire.com/file/4kew467y46ivyyz/multistorage-1.11.0-1.3.8-RB2.jar

**Comment by Mohron** [comment]
Should we assume a coremod serverside (aka Sponge) could be causing this? Or do you feel there could be a genuine issue here since the client is crashing?

Also, do you have to Increment the version where the server needs updated too :p

**Comment by ShetiPhian** [comment]
The client crash is due to a blank string making it into a method that doesn't support it.

At this time I have no idea what is causing the problem, just that the nbt data is missing when onItemRightClick tries to read it.

If RB2 no longer crashes and the bag still opens(*) then its just the client loosing the data, but if the bag no longer opens somehow the data is missing server side yet still saves.

(*) gui may display the wrong name but the correct inventory should still open

**Comment by Mohron** [comment]
Looks like it's not Sponge/Server related. One of our players just got this crash in Single Player when killing the Ender Dragon (random).
https://hastebin.com/xewuropixe.pas

**Comment by Cntrldfusion** [comment]
I have the same problem since updating in my mudpack.  Here are the crash reports.  Chest size doesn't seem to matter either.

[crash-2017-06-22_19.09.36-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/1096392/crash-2017-06-22_19.09.36-client.txt)
[crash-2017-06-22_19.14.53-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/1096393/crash-2017-06-22_19.14.53-client.txt)

**Comment by ShetiPhian** [comment]
Well, I've tried a work around but that has got it own problem.

The client needs the data at the time of opening the gui.
I can't rely on the itemstack nbt data due to mod interference.
Data must be sent from the sever to the client.
I can't use the default Forge provided open gui methods, because I need to send more data then it supports.
Creating my own packet and copying everything Forge did, enable the gui to open, BUT the mouse cursor is invisible until the game looses focus or the mouse leaves the game window.
So now I'm at a loss.

**Comment by Mohron** [comment]
This issue seemed to appear out of nowhere... Is it only effecting 1.11.2?

**Comment by ShetiPhian** [comment]
The reported bug only appears to be 1.11.2, as its hasn't been reported for any other version.
The gui issue is 1.12, I'm ready* to push out beta builds and figured I'd try to nip this bug first.
(* Forge no longer loads mods and coremods from the same jar, but the system to extract them doesn't work yet)

**Comment by ShetiPhian** [comment]
Here is a build that handles everything server side,
I'm using a workaround for the mouse issue (reset it every draw for the first second the gui is open)

http://www.mediafire.com/file/nu6kgi03js8ns8q/multistorage-1.11.0-1.3.8-RB3.jar

I wasn't going to increment the build version, but the server needs this one.
