### ISSUE TITLE
Alternate Logo's???

### ISSUE THREAD

**Issue by ArashiDragon** [ShetiPhian/Localizations-and-Issues#88]
Just an idea. Not sure if this is even possible (or worth the effort), but looking at your logo's/screenshots.

I was wondering if you could use a flag/banner you've made as the logo (craft it together with the spread for a custom logo?)

**Comment by ShetiPhian** [comment]
Now is the time to look into it as I'm currently reworking the mod to add more customization (going slow due to available time)
I was going to look into using blocks and items, but banners never crossed my mind.

**Comment by ShetiPhian** [comment]
@ArashiDragon 
Looks like my original ideas are going to be put on hold, due to time and planning :)
But I was able to increase customization via your suggestion.

![](https://lh3.googleusercontent.com/x_fHDS_k27d9aL8fYEDPJJ3SEhK8_Ky0-S_VxVpCPnEG81IWpx1BQdRenpI3CXXQPHE7j5x0jg8Hx3EyrGjziLOkeQRgr7gGep-cMQRSHU_FTV6T2lf_S-G7VFmVdn9cKOVF6ffC_XTvmPJra7nQiuSawH--gJJ9Mn-GvcYYF7gsnGLjPbxLOy7jcbtLXR-W6EAI6m-XlF4p3fmc973rA7tiv5x1NApdZQ3nJAHqWJL-g_ZfKnqwR8-djFk5Zl_xfHxRasQFjUsFifGO4rwMaUv0c4eL8a9d6LRWeEZmI7xr_ZLhwXbMUZnEyA2ZbbTG-luIzba5HQWSjzRFdyzsvmi9BBz64EsMmrNTYYGIlcIu2PMmiaZI3BtkLEEMRO1Ld7JenicLuDKvcqeyAOiUo8fJhBZPLhf5CgT2bDi2cgScvxpXK1_XHCS89rky4jr-Q50wjEU_pOcsNzvzLfOkIWL9aHSop8XXlLQ2suS5NvneopxqGzCpzGSlVjYAGr-aRPDO6iS63xNpm4HW3ul1L_JVcUfOPa6ErOutBtPM4S6fS89ahj5Yfx0ENGgjqWn1AAEHdQq-K6KuGApKuVROmntorJFIO5oNsqxQEuhvHpC3jNTiXmY1=w854-h480-no)

Its currently coded for 1.12, but it looks like 1.11 would be an easy back port. (1.10 is likely possible if you need it)

**Comment by ArashiDragon** [comment]
I think many will love the options.

**Comment by ShetiPhian** [comment]
Builds for 1.12, 1.11, and 1.10 are available on Curse
