### ISSUE TITLE
Platformer sometimes crashes server (Exception Ticking World)

### ISSUE THREAD

**Issue by TheLegitimantis** [ShetiPhian/Localizations-and-Issues#9]
Sometimes using the Platformer will crash my server. It seems to be caused by changing what the Platformer is making.

Here is my forge crash report: http://pastebin.com/9kb1Uqf6

And here is my server's general crash report: http://pastebin.com/RwmcvsYM

This crash is happening with Minecraft 1.10.2, Platforms 1.2.2, and Forge version 12.18.2.2114

**Comment by ShetiPhian** [comment]
The crash is due to something editing a list variable while its being iterated through.

The PlatFormer shouldn't be causing it.
When the type is changed I send a packet to the server, the server sets the new type and updates its output, then sets the needs update flag.
Minecraft syncs the tile on the next update cycle.

I'll run some tests, if you can find/provide steps that reliably produce the crash it would help a lot.

**Comment by TheLegitimantis** [comment]
Nothing specific seems to cause it.

Changing between what the Platformer is actually making is the only thing that can reliably cause it. For example, opening its UI displays the recipe for Wooden Platforms; clicking the right arrow button switches it to the next recipe. Clicking either arrow button seems to have a completely random chance of crashing my server.

No one specific recipe or page does it. Sometimes it happens and sometimes it doesn't.
