### ISSUE TITLE
Crash on 1.11.2 when using blaze powder on EnderTable

### ISSUE THREAD

**Issue by krwminer** [ShetiPhian/Localizations-and-Issues#98]
There is a client side crash that happens on 1.11.2 when you use blaze powder on the EnderTable.

I tested this on 1.12 version of your mods and it seems to work. I could not find the issue in the closed issue logs, but I might have missed it.

I just wanted to see if it was possible to have a fix for this for 1.11.2.

[crash-2017-08-01_10.51.00-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/1190980/crash-2017-08-01_10.51.00-client.txt)

**Comment by ShetiPhian** [comment]
Its another missed null itemstack.
(1.12 works because so much in the enchantment table was renamed, it was easier to copy it again and re-implement the ender table features.)

I wonder when all of the overlooked null stacks will be found/fixed, I've reread my code twice now yet some keep getting missed.

**Comment by ShetiPhian** [comment]
Fixed in 1.3.15
https://minecraft.curseforge.com/projects/terraqueous/files/2470598
