### ISSUE TITLE
[1.12] Endimium Ore not generating

### ISSUE THREAD

**Issue by angelnc1989** [ShetiPhian/Localizations-and-Issues#99]
Minecraft 1.12
Forge 14.21.1.2426
Terraqueous 1.4.0.3

Endimium Ore is not generating in The End for me. Neither on the main island nor on outer islands.
I checked in the main world I am playing in and a test world.
Everything else (Clouds, Burnium, Trees, Plants) is generating.

**Comment by ShetiPhian** [comment]
I just checked this in both of my test environments, Forge 2387 (1.12) and Forge 2452 (12.1)
Endimium is generating.

None of my generators run on the super flat world type unless the 'generateInFlatWorlds' config option is true. But since the others are generating either you already have that option enabled or that is not the world type your using.

If 'ignoreGenerationEvents' is false and another mod has flagged a chunk as generation complete, my generator will skip that chunk.

Has the end stone been replaced by another mod? The generator only replaces the original.

**Comment by angelnc1989** [comment]
The end stone is vanilla. The only mods that generate things in the end I have installed are Dimensional Ores and Quark.

**Comment by ShetiPhian** [comment]
It must be something else.
![](https://lh3.googleusercontent.com/5d7rUbb8pi0QKo-l_hsQ-adynXAFpXNJ2Pad8Ee96mVoRjFWwzT-OZaqotgErsYmmSAgeRDl9pK46nGRB9w4k6TTCjTagrzzRgagRNW0MiSaE3VKcxsPPWUFEPm-LmoUmaL_7jEfDGmUNE53T8xih2TOcr3SklvT1dHfJRHlBJH6UPpuSe_FZ_gKRiPCKpmxA3yqKVbU9J7dF3yUKmIG88U-Dd2of5nUyfOmLhodJRWiIGRwOELpUQ_CDgRuMkJH6OaImABN6P5zWzxMOEa8bYpsUuIkR6Ui2S6v7a7WBhll9HCcTUYq7yzIDWsuDaKaTj11h0lv0Woxsq0hkhYUvYlUvRDHFyoLPn4D9qNq5U3woi79BPCANyKjGwsmAUIKm_0aIJU4nSuaJ5IJg7jl73lcn8ilaZAo-J_hEYr3R38luUtZiYLfVoIBa17fv2jCrXZUPMS_qaX3hQaRM-FK1g7OMqhi-9C5vK5mp7OzNAurvF6nPKX4CpaGzAo0sKw121jzxOnrttqgAV0qTGaem_tS8T3F6uXuOaPmfBbY7k-6ksdMPPY-iYDODHeV3galXwYdqu50-B5DllYTc4rdmWhFeZ46xbCZBIEfVSjfcaDl6pekiNbj=w854-h480-no)
(Dimensional Ores, Quark and Terraqueous)

With Clouds, Burnium, Trees, Plants, etc. generating, then my generators are functioning.
If Dimensional Ores is generating then generation in the End isn't disabled.

Was Endimium generation disabled?
[ Configuration: generator > doodads > generateDoodad_Endimium ]

If not that only leaves no valid placement, so either too much is generating in the End not leaving enough top level EndStone, or the EndStone is not vanilla and wasn't replaced correctly. (it is possible for it to have 'minecraft' as the mod id and not be vanilla, just use 'minecraft' as the owner when registering it)
